import type {
  PaidPdfLocale,
} from "./premium-localization";
/* =========================================================
   TYPES
========================================================= */
type TranslationMap = Record<string, string>;
/* =========================================================
   HELPERS
========================================================= */
function buildTranslationMap(
  french: readonly string[],
  translated: readonly string[],
): TranslationMap {
  if (french.length !== translated.length) {
    throw new Error(
      `Translation length mismatch: ${french.length} French entries vs ${translated.length} translated entries`,
    );
  }

  return Object.fromEntries(
    french.map((text, index) => [
      text,
      translated[index],
    ]),
  );
}
function applyTranslations(
  source: string,
  translations: TranslationMap,
): string {
  let output = source;

  for (const [from, to] of Object.entries(translations)) {
    output = output.split(from).join(to);
  }

  return output;
}
/* =========================================================
   SOCIAL TITLES — FRENCH SOURCE
========================================================= */
const SOCIAL_TITLES_FR = [
  "Une année pour enrichir vos relations",
  "Votre vie sociale entre dans une nouvelle phase",
  "Des liens plus sincères se construisent",
  "Une année de rencontres et de rapprochements",
  "Votre entourage évolue avec vous",
  "Une nouvelle dynamique relationnelle s’installe",
  "Vos relations gagnent en profondeur",
  "Une année pour mieux choisir votre entourage",
] as const;
/* =========================================================
   SOCIAL TITLES — TRANSLATIONS
========================================================= */
const SOCIAL_TITLES_TRANSLATIONS: Record<
  Exclude<PaidPdfLocale, "fr">,
  readonly string[]
> = {
  en: [
    "A year to enrich your relationships",
    "Your social life enters a new phase",
    "More sincere connections are taking shape",
    "A year of encounters and closer connections",
    "Your social circle evolves with you",
    "A new relationship dynamic is taking shape",
    "Your relationships gain greater depth",
    "A year to choose your social circle more wisely",
],
  es: [
    "Un año para enriquecer tus relaciones",
    "Tu vida social entra en una nueva etapa",
    "Se construyen vínculos más sinceros",
    "Un año de encuentros y acercamientos",
    "Tu entorno evoluciona contigo",
    "Se instala una nueva dinámica relacional",
    "Tus relaciones ganan profundidad",
    "Un año para elegir mejor a las personas que te rodean",
],
  de: [
    "Ein Jahr, um Ihre Beziehungen zu bereichern",
    "Ihr Sozialleben tritt in eine neue Phase ein",
    "Aufrichtigere Verbindungen entstehen",
    "Ein Jahr voller Begegnungen und Annäherungen",
    "Ihr Umfeld entwickelt sich mit Ihnen",
    "Eine neue Beziehungsdynamik entsteht",
    "Ihre Beziehungen gewinnen an Tiefe",
    "Ein Jahr, um Ihr Umfeld bewusster zu wählen",
],
  it: [
    "Un anno per arricchire le vostre relazioni",
    "La vostra vita sociale entra in una nuova fase",
    "Si costruiscono legami più sinceri",
    "Un anno di incontri e avvicinamenti",
    "Le persone che vi circondano evolvono con voi",
    "Si instaura una nuova dinamica relazionale",
    "Le vostre relazioni acquistano profondità",
    "Un anno per scegliere meglio le persone che vi circondano",
],
  pt: [
    "Um ano para enriquecer seus relacionamentos",
    "Sua vida social entra em uma nova fase",
    "Vínculos mais sinceros estão se formando",
    "Um ano de encontros e aproximações",
    "As pessoas ao seu redor evoluem com você",
    "Uma nova dinâmica relacional está surgindo",
    "Seus relacionamentos ganham profundidade",
    "Um ano para escolher melhor as pessoas ao seu redor",
],
};
/* =========================================================
   SOCIAL TEXTS — FRENCH SOURCE
========================================================= */
const SOCIAL_TEXTS_FR = [
  "Votre vie sociale pourrait prendre davantage d’importance cette année. Certaines rencontres ou conversations vous aideront à mieux comprendre la place que vous occupez dans vos relations.",
  "Les prochains mois mettent l’accent sur vos échanges, vos amitiés et votre manière de créer des liens. Vous pourriez rechercher des relations plus sincères et plus équilibrées.",
  "Cette année vous invite à observer la qualité de votre entourage. Certaines relations vous apporteront de l’énergie, tandis que d’autres pourraient vous en demander davantage.",
  "Votre cercle social pourrait connaître une évolution importante. Une nouvelle proximité pourrait se créer pendant qu’une relation moins naturelle s’éloignera progressivement.",
  "Le climat relationnel favorise les conversations authentiques et les liens construits sur la confiance. Vous pourriez devenir plus sélectif dans vos fréquentations.",
  "Les prochains mois pourraient vous aider à reprendre contact avec une personne importante ou à approfondir une relation déjà présente.",
  "Votre besoin de partage augmente, mais vous souhaiterez surtout être entouré de personnes capables de respecter votre sensibilité et vos limites.",
  "Une période plus active commence dans votre vie sociale. Les invitations, les échanges et les nouvelles connaissances pourraient se multiplier.",
  "Cette année vous pousse à trouver un meilleur équilibre entre votre besoin de solitude et votre envie de rester connecté aux autres.",
  "Votre manière d’entrer en relation évolue. Vous pourriez rechercher moins de quantité et davantage de profondeur dans vos échanges.",
  "Votre présence sera appréciée lorsque vous resterez naturel, sans chercher à répondre à toutes les attentes de votre entourage.",
  "Une conversation spontanée pourrait vous apporter une idée, un soutien ou une nouvelle perspective.",
  "Vous pourriez ressentir le besoin de revoir la place occupée par certaines personnes dans votre quotidien.",
  "L’année favorise les échanges simples, honnêtes et sans sous-entendus inutiles.",
  "Une relation pourrait devenir plus fluide lorsque chacun exprimera clairement ses besoins.",
  "Vous pourriez être plus sensible à l’atmosphère de certains groupes. Choisissez les environnements dans lesquels vous vous sentez réellement à l’aise.",
  "Votre vie sociale gagnera en qualité lorsque vous cesserez d’entretenir des liens uniquement par habitude.",
  "Une personne pourrait se montrer plus présente que prévu. Prenez le temps d’observer ses intentions sans tirer de conclusion trop rapide.",
  "Les relations les plus solides seront celles où vous pourrez parler librement sans devoir constamment vous adapter.",
  "Une nouvelle dynamique pourrait s’installer dans votre entourage et modifier certaines habitudes sociales.",
  "Une amitié pourrait se renforcer grâce à une conversation plus personnelle ou à une expérience importante partagée au cours de l’année.",
  "Vous pourriez reprendre contact avec une personne perdue de vue depuis quelque temps.",
  "Une relation amicale pourrait demander une mise au point afin d’éviter qu’un malaise ne s’installe durablement.",
  "Un ami pourrait avoir besoin de votre écoute. Veillez toutefois à ne pas porter seul ses difficultés.",
  "Vous pourriez découvrir une nouvelle facette d’une personne que vous connaissez déjà.",
  "L’année favorise les amitiés fondées sur la loyauté, le respect et la réciprocité.",
  "Une invitation pourrait vous permettre de sortir de votre routine et de rencontrer des personnes intéressantes.",
  "Vous pourriez vous éloigner naturellement d’une relation devenue moins compatible avec votre évolution actuelle.",
  "Un geste simple pourrait raviver une amitié que vous croyiez affaiblie.",
  "Votre entourage pourrait vous rappeler l’importance de demander du soutien plutôt que de tout gérer seul.",
  "Une situation familiale pourrait demander davantage de patience et de communication au cours de l’année.",
  "Une conversation importante pourrait permettre de clarifier une incompréhension ancienne.",
  "Vous pourriez ressentir le besoin de protéger davantage votre espace personnel face aux attentes de votre famille.",
  "Un membre de votre entourage familial pourrait vous surprendre par son soutien ou sa compréhension.",
  "Une responsabilité familiale pourrait modifier temporairement votre organisation.",
  "L’année vous invite à éviter les réactions automatiques dans une relation chargée d’émotions anciennes.",
  "Un rapprochement pourrait devenir possible si chacun accepte de parler avec plus de sincérité.",
  "Vous pourriez devoir rappeler une limite qui n’a pas été suffisamment respectée.",
  "Une activité ou un événement partagé pourrait améliorer l’ambiance familiale.",
  "Votre calme vous aidera à ne pas amplifier une tension qui pourrait se résoudre plus simplement que prévu.",
  "Une nouvelle rencontre pourrait vous ouvrir à un univers, une idée ou une activité différente.",
  "Vous pourriez faire la connaissance d’une personne avec qui la conversation semblera immédiatement naturelle.",
  "Un contexte professionnel, social ou numérique pourrait favoriser une nouvelle relation intéressante.",
  "Une rencontre discrète pourrait devenir plus importante avec le temps. Ne vous fiez pas uniquement à la première impression.",
  "L’année favorise les liens créés autour d’un intérêt, d’un projet ou d’une valeur commune.",
  "Vous pourriez attirer des personnes qui reflètent votre évolution récente.",
  "Une nouvelle connaissance pourrait vous aider à sortir d’une manière de penser devenue trop limitée.",
  "Une relation pourrait commencer lentement, mais gagner progressivement en confiance et en profondeur.",
  "Vous pourriez être présenté à une personne capable de jouer un rôle utile dans un projet futur.",
  "Une rencontre inattendue pourrait raviver votre envie de participer davantage à la vie sociale.",
  "Vos échanges gagneront en fluidité si vous exprimez directement ce que vous ressentez ou attendez.",
  "Évitez de supposer que les autres comprennent automatiquement vos intentions.",
  "Une formulation plus douce vous permettra de transmettre un message important sans diminuer sa clarté.",
  "Vous pourriez être amené à corriger une information ou à clarifier une parole mal interprétée.",
  "Votre écoute jouera un rôle aussi important que vos paroles dans une conversation sensible.",
  "Une discussion retardée mérite peut-être d’avoir lieu avant qu’un malaise ne s’installe davantage.",
  "Vous pourriez découvrir qu’une personne partage davantage votre point de vue que vous ne le pensiez.",
  "L’année favorise les échanges honnêtes, mais il faudra éviter les paroles prononcées sous le coup de l’impatience.",
  "Un message, un appel ou une conversation pourrait modifier positivement votre perception d’une relation.",
  "Votre capacité à poser les bonnes questions vous aidera à mieux comprendre les motivations d’une personne.",
  "Le début de l’année favorisera le tri dans vos relations et la clarification de certaines attentes.",
  "Le printemps pourrait apporter davantage d’invitations, de rencontres et d’échanges spontanés.",
  "Le milieu de l’année favorisera les rapprochements, les projets partagés et les nouvelles collaborations.",
  "L’été pourrait rendre votre vie sociale plus active et vous aider à sortir de certaines habitudes.",
  "Le début de l’automne sera propice aux conversations importantes et aux mises au point constructives.",
  "La fin de l’année favorisera les retrouvailles, les bilans relationnels et les liens les plus sincères.",
  "Une période plus calme vous permettra de mieux comprendre quelles relations méritent votre énergie.",
  "Le deuxième semestre pourrait apporter une rencontre capable de prendre progressivement une place importante.",
  "Certaines relations évolueront rapidement, tandis que d’autres demanderont davantage de temps et de patience.",
  "Les périodes les plus favorables seront celles où vous accepterez de rester vous-même sans chercher à satisfaire tout le monde.",
  "Le principal défi sera de ne pas vous épuiser à maintenir des relations qui ne sont plus réciproques.",
  "Vous pourriez avoir tendance à accepter une invitation ou une demande alors que vous avez réellement besoin de repos.",
  "Une remarque pourrait vous toucher plus fortement que prévu. Prenez le temps de vérifier l’intention réelle avant de réagir.",
  "Le besoin d’éviter un conflit pourrait vous pousser à taire une limite pourtant importante.",
  "Vous pourriez vous sentir responsable de l’humeur ou du bien-être d’une personne de votre entourage.",
  "Une relation pourrait devenir plus exigeante si les attentes restent implicites.",
  "Le défi consistera à ne pas vous isoler complètement après une déception relationnelle.",
  "Vous pourriez accorder trop d’importance à l’opinion d’un groupe qui ne vous connaît pas réellement.",
  "Une tension ancienne pourrait réapparaître si elle n’a jamais été véritablement réglée.",
  "Le désir de préserver l’harmonie pourrait vous faire accepter un comportement qui ne vous convient pas.",
  "Privilégiez les relations dans lesquelles vous pouvez rester vous-même sans devoir constamment vous justifier.",
  "Exprimez vos limites dès les premiers signes d’inconfort plutôt que d’attendre l’accumulation.",
  "Accordez votre temps aux personnes qui vous offrent une présence aussi sincère que la vôtre.",
  "Ne confondez pas disponibilité et obligation permanente.",
  "Prenez l’initiative d’un échange lorsque vous sentez qu’une relation mérite d’être préservée.",
  "Éloignez-vous temporairement d’une situation sociale lorsque votre énergie devient trop basse.",
  "Laissez une nouvelle relation évoluer naturellement sans chercher à définir trop rapidement sa place.",
  "Évitez de répondre immédiatement à une parole qui vous blesse. Le recul vous aidera à choisir une réponse plus juste.",
  "Soyez attentif aux actes autant qu’aux paroles lorsque vous évaluez la fiabilité d’une personne.",
  "Cherchez un équilibre entre votre besoin de proximité et votre besoin d’indépendance.",
  "Cette année peut enrichir votre vie relationnelle si vous privilégiez les liens sincères, équilibrés et respectueux.",
  "Votre entourage évoluera favorablement lorsque vous ferez davantage de place aux relations qui correspondent à vos valeurs.",
  "Les prochains mois pourraient renforcer une amitié, clarifier une relation ou favoriser une nouvelle rencontre importante.",
  "Vous pourriez terminer l’année avec une vision plus claire des personnes sur lesquelles vous pouvez réellement compter.",
  "Votre vie sociale gagnera en profondeur à mesure que vous protégerez mieux votre énergie et vos limites.",
  "Une relation pourrait devenir plus solide grâce à une communication directe et bienveillante.",
  "Cette année vous rappelle qu’une relation saine doit offrir autant de sécurité que de liberté.",
  "Votre capacité à choisir votre entourage avec discernement améliorera votre équilibre émotionnel.",
  "Une nouvelle dynamique relationnelle pourrait vous apporter davantage de légèreté et de confiance.",
  "En restant fidèle à vos besoins, vous attirerez des échanges plus authentiques et plus satisfaisants.",
] as const;
/* =========================================================
   SOCIAL TEXTS — TRANSLATIONS
========================================================= */
const SOCIAL_TEXTS_TRANSLATIONS: Record<
  Exclude<PaidPdfLocale, "fr">,
  readonly string[]
> = {
  en: [
    "Your social life could become more important this year. Certain encounters or conversations will help you better understand the place you occupy in your relationships.",
    "The coming months emphasize your exchanges, friendships, and the way you create connections. You may seek relationships that are more sincere and balanced.",
    "This year invites you to observe the quality of the people around you. Some relationships will give you energy, while others may require more from you.",
    "Your social circle could undergo an important change. A new closeness may develop while a less natural relationship gradually fades.",
    "The relational climate favors authentic conversations and connections built on trust. You may become more selective about the people you spend time with.",
    "The coming months could help you reconnect with someone important or deepen an existing relationship.",
    "Your need to share increases, but above all you will want to be surrounded by people who can respect your sensitivity and your boundaries.",
    "A more active period begins in your social life. Invitations, conversations, and new acquaintances could multiply.",
    "This year pushes you to find a better balance between your need for solitude and your desire to stay connected with others.",
    "The way you relate to others is evolving. You may seek fewer relationships, but greater depth in your exchanges.",
    "Your presence will be appreciated when you remain natural, without trying to meet every expectation of those around you.",
    "A spontaneous conversation could bring you an idea, support, or a new perspective.",
    "You may feel the need to reconsider the place certain people occupy in your daily life.",
    "The year favors simple, honest exchanges without unnecessary hidden meanings.",
    "A relationship could become more fluid when each person clearly expresses their needs.",
    "You may be more sensitive to the atmosphere of certain groups. Choose environments where you genuinely feel comfortable.",
    "Your social life will improve in quality when you stop maintaining connections solely out of habit.",
    "Someone could be more present than expected. Take time to observe their intentions without drawing conclusions too quickly.",
    "The strongest relationships will be those in which you can speak freely without constantly having to adapt.",
    "A new dynamic could settle into your social circle and change certain social habits.",
    "A friendship could grow stronger through a more personal conversation or an important experience shared during the year.",
    "You may reconnect with someone you have not seen for some time.",
    "A friendship may require a clarification to prevent discomfort from becoming long-lasting.",
    "A friend may need your listening ear. However, be careful not to carry their difficulties alone.",
    "You may discover a new side of someone you already know.",
    "The year favors friendships based on loyalty, respect, and reciprocity.",
    "An invitation could help you break out of your routine and meet interesting people.",
    "You may naturally drift away from a relationship that has become less compatible with your current growth.",
    "A simple gesture could revive a friendship you thought had weakened.",
    "The people around you could remind you of the importance of asking for support instead of handling everything alone.",
    "A family situation may require more patience and communication during the year.",
    "An important conversation could help clarify an old misunderstanding.",
    "You may feel the need to protect your personal space more firmly from family expectations.",
    "A family member could surprise you with their support or understanding.",
    "A family responsibility could temporarily change your organization.",
    "The year invites you to avoid automatic reactions in a relationship charged with old emotions.",
    "A closer connection could become possible if everyone agrees to speak with greater sincerity.",
    "You may need to restate a boundary that has not been sufficiently respected.",
    "A shared activity or event could improve the family atmosphere.",
    "Your calmness will help you avoid amplifying a tension that could be resolved more simply than expected.",
    "A new encounter could open you up to a different world, idea, or activity.",
    "You may meet someone with whom conversation feels immediately natural.",
    "A professional, social, or digital context could encourage an interesting new relationship.",
    "A subtle encounter could become more important over time. Do not rely only on the first impression.",
    "The year favors connections created around a shared interest, project, or value.",
    "You may attract people who reflect your recent growth.",
    "A new acquaintance could help you move beyond a way of thinking that has become too limited.",
    "A relationship could begin slowly but gradually gain trust and depth.",
    "You may be introduced to someone who could play a useful role in a future project.",
    "An unexpected encounter could rekindle your desire to participate more actively in social life.",
    "Your conversations will flow more easily if you directly express what you feel or expect.",
    "Avoid assuming that others automatically understand your intentions.",
    "A gentler wording will allow you to convey an important message without reducing its clarity.",
    "You may need to correct information or clarify something that was misunderstood.",
    "Your listening skills will play as important a role as your words in a sensitive conversation.",
    "A delayed conversation may need to happen before discomfort grows further.",
    "You may discover that someone shares your point of view more than you thought.",
    "The year favors honest exchanges, but you will need to avoid words spoken out of impatience.",
    "A message, call, or conversation could positively change your perception of a relationship.",
    "Your ability to ask the right questions will help you better understand someone’s motivations.",
    "The beginning of the year will favor sorting through your relationships and clarifying certain expectations.",
    "Spring could bring more invitations, encounters, and spontaneous exchanges.",
    "The middle of the year will favor closer connections, shared projects, and new collaborations.",
    "Summer could make your social life more active and help you break out of certain habits.",
    "Early autumn will be favorable for important conversations and constructive clarifications.",
    "The end of the year will favor reunions, relationship reviews, and the most sincere connections.",
    "A quieter period will allow you to better understand which relationships deserve your energy.",
    "The second half of the year could bring an encounter that gradually takes on an important place.",
    "Some relationships will evolve quickly, while others will require more time and patience.",
    "The most favorable periods will be those when you accept being yourself without trying to please everyone.",
    "The main challenge will be not exhausting yourself trying to maintain relationships that are no longer reciprocal.",
    "You may tend to accept an invitation or request when you actually need rest.",
    "A remark could affect you more strongly than expected. Take time to check the real intention before reacting.",
    "The need to avoid conflict could lead you to remain silent about an important boundary.",
    "You may feel responsible for the mood or well-being of someone around you.",
    "A relationship could become more demanding if expectations remain unspoken.",
    "The challenge will be not to isolate yourself completely after a relational disappointment.",
    "You may give too much importance to the opinion of a group that does not truly know you.",
    "An old tension could resurface if it was never truly resolved.",
    "The desire to preserve harmony could make you accept behavior that does not suit you.",
    "Prioritize relationships in which you can remain yourself without constantly having to justify yourself.",
    "Express your boundaries at the first signs of discomfort rather than waiting for frustration to accumulate.",
    "Give your time to people who offer you a presence as sincere as your own.",
    "Do not confuse availability with permanent obligation.",
    "Take the initiative to start a conversation when you feel a relationship deserves to be preserved.",
    "Step away temporarily from a social situation when your energy becomes too low.",
    "Allow a new relationship to evolve naturally without trying to define its place too quickly.",
    "Avoid responding immediately to words that hurt you. Taking a step back will help you choose a fairer response.",
    "Pay attention to actions as much as words when evaluating someone’s reliability.",
    "Seek a balance between your need for closeness and your need for independence.",
    "This year can enrich your relational life if you prioritize sincere, balanced, and respectful connections.",
    "Your social circle will evolve positively when you make more room for relationships that align with your values.",
    "The coming months could strengthen a friendship, clarify a relationship, or encourage an important new encounter.",
    "You may end the year with a clearer understanding of the people you can truly rely on.",
    "Your social life will gain depth as you better protect your energy and your boundaries.",
    "A relationship could become stronger through direct and caring communication.",
    "This year reminds you that a healthy relationship should offer as much security as freedom.",
    "Your ability to choose the people around you wisely will improve your emotional balance.",
    "A new relational dynamic could bring you more lightness and confidence.",
    "By staying true to your needs, you will attract more authentic and satisfying exchanges.",
],
  es: [
    "Tu vida social podría adquirir mayor importancia este año. Algunos encuentros o conversaciones te ayudarán a comprender mejor el lugar que ocupas en tus relaciones.",
    "Los próximos meses ponen el acento en tus intercambios, tus amistades y tu manera de crear vínculos. Podrías buscar relaciones más sinceras y equilibradas.",
    "Este año te invita a observar la calidad de tu entorno. Algunas relaciones te aportarán energía, mientras que otras podrían exigirte más.",
    "Tu círculo social podría experimentar una evolución importante. Podría surgir una nueva cercanía mientras una relación menos natural se aleja progresivamente.",
    "El clima relacional favorece las conversaciones auténticas y los vínculos construidos sobre la confianza. Podrías volverte más selectivo con las personas que frecuentas.",
    "Los próximos meses podrían ayudarte a retomar el contacto con una persona importante o a profundizar una relación ya existente.",
    "Tu necesidad de compartir aumenta, pero sobre todo querrás rodearte de personas capaces de respetar tu sensibilidad y tus límites.",
    "Comienza un período más activo en tu vida social. Las invitaciones, los intercambios y las nuevas amistades podrían multiplicarse.",
    "Este año te impulsa a encontrar un mejor equilibrio entre tu necesidad de soledad y tu deseo de mantenerte conectado con los demás.",
    "Tu manera de relacionarte evoluciona. Podrías buscar menos cantidad y más profundidad en tus intercambios.",
    "Tu presencia será apreciada cuando te muestres natural, sin intentar responder a todas las expectativas de quienes te rodean.",
    "Una conversación espontánea podría aportarte una idea, apoyo o una nueva perspectiva.",
    "Podrías sentir la necesidad de revisar el lugar que ocupan ciertas personas en tu vida cotidiana.",
    "El año favorece los intercambios sencillos, honestos y sin dobles sentidos innecesarios.",
    "Una relación podría volverse más fluida cuando cada persona exprese claramente sus necesidades.",
    "Podrías ser más sensible al ambiente de ciertos grupos. Elige los entornos en los que realmente te sientas cómodo.",
    "Tu vida social ganará en calidad cuando dejes de mantener vínculos únicamente por costumbre.",
    "Una persona podría mostrarse más presente de lo previsto. Tómate el tiempo de observar sus intenciones sin sacar conclusiones demasiado rápido.",
    "Las relaciones más sólidas serán aquellas en las que puedas hablar libremente sin tener que adaptarte constantemente.",
    "Una nueva dinámica podría instalarse en tu entorno y modificar ciertos hábitos sociales.",
    "Una amistad podría fortalecerse gracias a una conversación más personal o a una experiencia importante compartida durante el año.",
    "Podrías retomar el contacto con una persona a la que no ves desde hace algún tiempo.",
    "Una relación de amistad podría necesitar una aclaración para evitar que un malestar se instale de manera duradera.",
    "Un amigo podría necesitar que lo escuches. Sin embargo, procura no cargar tú solo con sus dificultades.",
    "Podrías descubrir una nueva faceta de una persona que ya conoces.",
    "El año favorece las amistades basadas en la lealtad, el respeto y la reciprocidad.",
    "Una invitación podría ayudarte a salir de tu rutina y conocer personas interesantes.",
    "Podrías alejarte de manera natural de una relación que se ha vuelto menos compatible con tu evolución actual.",
    "Un gesto sencillo podría reavivar una amistad que creías debilitada.",
    "Tu entorno podría recordarte la importancia de pedir apoyo en lugar de gestionarlo todo tú solo.",
    "Una situación familiar podría requerir más paciencia y comunicación a lo largo del año.",
    "Una conversación importante podría permitir aclarar un antiguo malentendido.",
    "Podrías sentir la necesidad de proteger más tu espacio personal frente a las expectativas de tu familia.",
    "Un miembro de tu familia podría sorprenderte por su apoyo o comprensión.",
    "Una responsabilidad familiar podría modificar temporalmente tu organización.",
    "El año te invita a evitar reacciones automáticas en una relación cargada de emociones antiguas.",
    "Un acercamiento podría hacerse posible si todos aceptan hablar con mayor sinceridad.",
    "Podrías tener que recordar un límite que no ha sido suficientemente respetado.",
    "Una actividad o un evento compartido podría mejorar el ambiente familiar.",
    "Tu calma te ayudará a no amplificar una tensión que podría resolverse de manera más sencilla de lo previsto.",
    "Un nuevo encuentro podría abrirte a un universo, una idea o una actividad diferente.",
    "Podrías conocer a una persona con quien la conversación parezca inmediatamente natural.",
    "Un contexto profesional, social o digital podría favorecer una nueva relación interesante.",
    "Un encuentro discreto podría adquirir mayor importancia con el tiempo. No te fíes únicamente de la primera impresión.",
    "El año favorece los vínculos creados alrededor de un interés, un proyecto o un valor común.",
    "Podrías atraer a personas que reflejen tu evolución reciente.",
    "Una nueva amistad podría ayudarte a salir de una manera de pensar que se ha vuelto demasiado limitada.",
    "Una relación podría comenzar lentamente, pero ganar progresivamente confianza y profundidad.",
    "Podrían presentarte a una persona capaz de desempeñar un papel útil en un proyecto futuro.",
    "Un encuentro inesperado podría reavivar tus ganas de participar más en la vida social.",
    "Tus intercambios serán más fluidos si expresas directamente lo que sientes o esperas.",
    "Evita suponer que los demás comprenden automáticamente tus intenciones.",
    "Una formulación más suave te permitirá transmitir un mensaje importante sin reducir su claridad.",
    "Podrías tener que corregir una información o aclarar unas palabras mal interpretadas.",
    "Tu capacidad de escuchar tendrá un papel tan importante como tus palabras en una conversación delicada.",
    "Quizá sea necesario tener una conversación aplazada antes de que el malestar aumente.",
    "Podrías descubrir que una persona comparte tu punto de vista más de lo que pensabas.",
    "El año favorece los intercambios honestos, pero será importante evitar palabras pronunciadas bajo el impulso de la impaciencia.",
    "Un mensaje, una llamada o una conversación podría cambiar positivamente tu percepción de una relación.",
    "Tu capacidad para hacer las preguntas adecuadas te ayudará a comprender mejor las motivaciones de una persona.",
    "El comienzo del año favorecerá una selección en tus relaciones y la aclaración de ciertas expectativas.",
    "La primavera podría traer más invitaciones, encuentros e intercambios espontáneos.",
    "La mitad del año favorecerá los acercamientos, los proyectos compartidos y las nuevas colaboraciones.",
    "El verano podría hacer que tu vida social sea más activa y ayudarte a salir de ciertos hábitos.",
    "El comienzo del otoño será propicio para conversaciones importantes y aclaraciones constructivas.",
    "El final del año favorecerá los reencuentros, los balances relacionales y los vínculos más sinceros.",
    "Un período más tranquilo te permitirá comprender mejor qué relaciones merecen tu energía.",
    "La segunda mitad del año podría traer un encuentro capaz de ocupar progresivamente un lugar importante.",
    "Algunas relaciones evolucionarán rápidamente, mientras que otras requerirán más tiempo y paciencia.",
    "Los períodos más favorables serán aquellos en los que aceptes ser tú mismo sin intentar satisfacer a todo el mundo.",
    "El principal desafío será no agotarte manteniendo relaciones que ya no son recíprocas.",
    "Podrías tender a aceptar una invitación o una petición cuando en realidad necesitas descansar.",
    "Un comentario podría afectarte más de lo previsto. Tómate el tiempo de comprobar la verdadera intención antes de reaccionar.",
    "La necesidad de evitar un conflicto podría llevarte a callar un límite que, sin embargo, es importante.",
    "Podrías sentirte responsable del estado de ánimo o del bienestar de una persona de tu entorno.",
    "Una relación podría volverse más exigente si las expectativas permanecen implícitas.",
    "El desafío consistirá en no aislarte completamente después de una decepción relacional.",
    "Podrías dar demasiada importancia a la opinión de un grupo que realmente no te conoce.",
    "Una antigua tensión podría reaparecer si nunca se resolvió de verdad.",
    "El deseo de preservar la armonía podría llevarte a aceptar un comportamiento que no te conviene.",
    "Da prioridad a las relaciones en las que puedas seguir siendo tú mismo sin tener que justificarte constantemente.",
    "Expresa tus límites desde las primeras señales de incomodidad en lugar de esperar a que se acumulen.",
    "Dedica tu tiempo a las personas que te ofrecen una presencia tan sincera como la tuya.",
    "No confundas disponibilidad con obligación permanente.",
    "Toma la iniciativa de conversar cuando sientas que una relación merece ser preservada.",
    "Aléjate temporalmente de una situación social cuando tu energía sea demasiado baja.",
    "Deja que una nueva relación evolucione de manera natural sin intentar definir demasiado rápido el lugar que ocupa.",
    "Evita responder inmediatamente a unas palabras que te hieran. Tomar distancia te ayudará a elegir una respuesta más justa.",
    "Presta atención a los actos tanto como a las palabras cuando evalúes la fiabilidad de una persona.",
    "Busca un equilibrio entre tu necesidad de cercanía y tu necesidad de independencia.",
    "Este año puede enriquecer tu vida relacional si das prioridad a los vínculos sinceros, equilibrados y respetuosos.",
    "Tu entorno evolucionará favorablemente cuando des más espacio a las relaciones que correspondan a tus valores.",
    "Los próximos meses podrían fortalecer una amistad, aclarar una relación o favorecer un nuevo encuentro importante.",
    "Podrías terminar el año con una visión más clara de las personas con las que realmente puedes contar.",
    "Tu vida social ganará profundidad a medida que protejas mejor tu energía y tus límites.",
    "Una relación podría volverse más sólida gracias a una comunicación directa y amable.",
    "Este año te recuerda que una relación sana debe ofrecer tanta seguridad como libertad.",
    "Tu capacidad para elegir tu entorno con discernimiento mejorará tu equilibrio emocional.",
    "Una nueva dinámica relacional podría aportarte más ligereza y confianza.",
    "Si te mantienes fiel a tus necesidades, atraerás intercambios más auténticos y satisfactorios.",
],
  de: [
    "Ihr Sozialleben könnte in diesem Jahr an Bedeutung gewinnen. Bestimmte Begegnungen oder Gespräche werden Ihnen helfen, besser zu verstehen, welchen Platz Sie in Ihren Beziehungen einnehmen.",
    "Die kommenden Monate legen den Schwerpunkt auf Ihre Gespräche, Freundschaften und die Art, wie Sie Verbindungen schaffen. Sie könnten nach aufrichtigeren und ausgeglicheneren Beziehungen suchen.",
    "Dieses Jahr lädt Sie dazu ein, die Qualität Ihres Umfelds zu beobachten. Manche Beziehungen werden Ihnen Energie geben, während andere mehr von Ihnen verlangen könnten.",
    "Ihr sozialer Kreis könnte sich deutlich verändern. Eine neue Nähe könnte entstehen, während sich eine weniger natürliche Beziehung allmählich entfernt.",
    "Das Beziehungsklima begünstigt authentische Gespräche und Verbindungen, die auf Vertrauen beruhen. Sie könnten wählerischer werden, mit wem Sie Ihre Zeit verbringen.",
    "Die kommenden Monate könnten Ihnen helfen, wieder Kontakt zu einer wichtigen Person aufzunehmen oder eine bestehende Beziehung zu vertiefen.",
    "Ihr Bedürfnis nach Austausch wächst, doch vor allem möchten Sie von Menschen umgeben sein, die Ihre Sensibilität und Ihre Grenzen respektieren können.",
    "Eine aktivere Phase beginnt in Ihrem Sozialleben. Einladungen, Gespräche und neue Bekanntschaften könnten zunehmen.",
    "Dieses Jahr fordert Sie dazu auf, ein besseres Gleichgewicht zwischen Ihrem Bedürfnis nach Rückzug und Ihrem Wunsch nach Verbindung mit anderen zu finden.",
    "Ihre Art, Beziehungen einzugehen, entwickelt sich weiter. Sie könnten weniger Kontakte, dafür aber mehr Tiefe in Ihren Gesprächen suchen.",
    "Ihre Anwesenheit wird geschätzt, wenn Sie natürlich bleiben, ohne zu versuchen, alle Erwartungen Ihres Umfelds zu erfüllen.",
    "Ein spontanes Gespräch könnte Ihnen eine Idee, Unterstützung oder eine neue Perspektive bringen.",
    "Sie könnten das Bedürfnis verspüren, den Platz bestimmter Personen in Ihrem Alltag neu zu bewerten.",
    "Das Jahr begünstigt einfache, ehrliche Gespräche ohne unnötige Andeutungen.",
    "Eine Beziehung könnte leichter werden, wenn beide Seiten ihre Bedürfnisse klar ausdrücken.",
    "Sie könnten empfindlicher auf die Atmosphäre bestimmter Gruppen reagieren. Wählen Sie Umfelder, in denen Sie sich wirklich wohlfühlen.",
    "Ihr Sozialleben wird an Qualität gewinnen, wenn Sie aufhören, Verbindungen nur aus Gewohnheit aufrechtzuerhalten.",
    "Jemand könnte präsenter sein als erwartet. Nehmen Sie sich Zeit, die Absichten dieser Person zu beobachten, ohne zu schnell Schlüsse zu ziehen.",
    "Die stabilsten Beziehungen werden jene sein, in denen Sie frei sprechen können, ohne sich ständig anpassen zu müssen.",
    "Eine neue Dynamik könnte sich in Ihrem Umfeld etablieren und bestimmte soziale Gewohnheiten verändern.",
    "Eine Freundschaft könnte durch ein persönlicheres Gespräch oder ein wichtiges gemeinsames Erlebnis im Laufe des Jahres stärker werden.",
    "Sie könnten wieder Kontakt zu jemandem aufnehmen, den Sie seit einiger Zeit aus den Augen verloren haben.",
    "Eine Freundschaft könnte eine Klärung benötigen, damit sich ein Unbehagen nicht dauerhaft festsetzt.",
    "Ein Freund könnte Ihre Aufmerksamkeit und Ihr Zuhören brauchen. Achten Sie jedoch darauf, seine Schwierigkeiten nicht allein zu tragen.",
    "Sie könnten eine neue Seite an jemandem entdecken, den Sie bereits kennen.",
    "Das Jahr begünstigt Freundschaften, die auf Loyalität, Respekt und Gegenseitigkeit beruhen.",
    "Eine Einladung könnte Ihnen helfen, aus Ihrer Routine auszubrechen und interessante Menschen kennenzulernen.",
    "Sie könnten sich ganz natürlich von einer Beziehung entfernen, die nicht mehr zu Ihrer aktuellen Entwicklung passt.",
    "Eine einfache Geste könnte eine Freundschaft wiederbeleben, die Sie für geschwächt hielten.",
    "Ihr Umfeld könnte Sie daran erinnern, wie wichtig es ist, Unterstützung zu erbitten, statt alles allein zu bewältigen.",
    "Eine familiäre Situation könnte im Laufe des Jahres mehr Geduld und Kommunikation erfordern.",
    "Ein wichtiges Gespräch könnte helfen, ein altes Missverständnis zu klären.",
    "Sie könnten das Bedürfnis verspüren, Ihren persönlichen Raum gegenüber familiären Erwartungen stärker zu schützen.",
    "Ein Familienmitglied könnte Sie mit seiner Unterstützung oder seinem Verständnis überraschen.",
    "Eine familiäre Verantwortung könnte Ihre Organisation vorübergehend verändern.",
    "Das Jahr lädt Sie dazu ein, automatische Reaktionen in einer Beziehung zu vermeiden, die mit alten Emotionen belastet ist.",
    "Eine Annäherung könnte möglich werden, wenn alle bereit sind, aufrichtiger miteinander zu sprechen.",
    "Sie könnten eine Grenze erneut deutlich machen müssen, die bisher nicht ausreichend respektiert wurde.",
    "Eine gemeinsame Aktivität oder Veranstaltung könnte die familiäre Atmosphäre verbessern.",
    "Ihre Ruhe wird Ihnen helfen, eine Spannung nicht unnötig zu verstärken, die sich einfacher lösen könnte als erwartet.",
    "Eine neue Begegnung könnte Ihnen eine andere Welt, Idee oder Aktivität eröffnen.",
    "Sie könnten jemanden kennenlernen, mit dem sich das Gespräch sofort natürlich anfühlt.",
    "Ein beruflicher, sozialer oder digitaler Kontext könnte eine interessante neue Beziehung begünstigen.",
    "Eine unscheinbare Begegnung könnte mit der Zeit wichtiger werden. Verlassen Sie sich nicht nur auf den ersten Eindruck.",
    "Das Jahr begünstigt Verbindungen, die rund um ein gemeinsames Interesse, Projekt oder einen gemeinsamen Wert entstehen.",
    "Sie könnten Menschen anziehen, die Ihre jüngste Entwicklung widerspiegeln.",
    "Eine neue Bekanntschaft könnte Ihnen helfen, eine Denkweise zu überwinden, die zu begrenzt geworden ist.",
    "Eine Beziehung könnte langsam beginnen, aber nach und nach an Vertrauen und Tiefe gewinnen.",
    "Sie könnten jemandem vorgestellt werden, der in einem zukünftigen Projekt eine nützliche Rolle spielen kann.",
    "Eine unerwartete Begegnung könnte Ihre Lust neu beleben, aktiver am sozialen Leben teilzunehmen.",
    "Ihre Gespräche werden flüssiger verlaufen, wenn Sie direkt ausdrücken, was Sie fühlen oder erwarten.",
    "Vermeiden Sie die Annahme, dass andere Ihre Absichten automatisch verstehen.",
    "Eine sanftere Formulierung wird es Ihnen ermöglichen, eine wichtige Botschaft zu vermitteln, ohne an Klarheit zu verlieren.",
    "Sie könnten eine Information korrigieren oder eine missverstandene Aussage klarstellen müssen.",
    "Ihr Zuhören wird in einem sensiblen Gespräch eine ebenso wichtige Rolle spielen wie Ihre Worte.",
    "Ein aufgeschobenes Gespräch sollte vielleicht stattfinden, bevor sich das Unbehagen weiter verstärkt.",
    "Sie könnten feststellen, dass jemand Ihren Standpunkt stärker teilt, als Sie gedacht haben.",
    "Das Jahr begünstigt ehrliche Gespräche, doch Sie sollten Worte vermeiden, die aus Ungeduld heraus gesprochen werden.",
    "Eine Nachricht, ein Anruf oder ein Gespräch könnte Ihre Wahrnehmung einer Beziehung positiv verändern.",
    "Ihre Fähigkeit, die richtigen Fragen zu stellen, wird Ihnen helfen, die Beweggründe einer Person besser zu verstehen.",
    "Der Jahresbeginn begünstigt eine Klärung Ihrer Beziehungen und bestimmter Erwartungen.",
    "Der Frühling könnte mehr Einladungen, Begegnungen und spontane Gespräche bringen.",
    "Die Jahresmitte begünstigt Annäherungen, gemeinsame Projekte und neue Kooperationen.",
    "Der Sommer könnte Ihr Sozialleben aktiver machen und Ihnen helfen, bestimmte Gewohnheiten zu verlassen.",
    "Der Beginn des Herbstes eignet sich für wichtige Gespräche und konstruktive Klärungen.",
    "Das Jahresende begünstigt Wiedersehen, Beziehungsauswertungen und die aufrichtigsten Verbindungen.",
    "Eine ruhigere Phase wird Ihnen helfen, besser zu erkennen, welche Beziehungen Ihre Energie verdienen.",
    "Die zweite Jahreshälfte könnte eine Begegnung bringen, die nach und nach einen wichtigen Platz einnimmt.",
    "Manche Beziehungen werden sich schnell entwickeln, während andere mehr Zeit und Geduld benötigen.",
    "Die günstigsten Phasen werden jene sein, in denen Sie bereit sind, Sie selbst zu bleiben, ohne es allen recht machen zu wollen.",
    "Die größte Herausforderung wird darin bestehen, sich nicht dabei zu erschöpfen, Beziehungen aufrechtzuerhalten, die nicht mehr gegenseitig sind.",
    "Sie könnten dazu neigen, eine Einladung oder Bitte anzunehmen, obwohl Sie eigentlich Ruhe brauchen.",
    "Eine Bemerkung könnte Sie stärker treffen als erwartet. Nehmen Sie sich Zeit, die tatsächliche Absicht zu prüfen, bevor Sie reagieren.",
    "Der Wunsch, einen Konflikt zu vermeiden, könnte Sie dazu bringen, eine wichtige Grenze nicht auszusprechen.",
    "Sie könnten sich für die Stimmung oder das Wohlbefinden einer Person in Ihrem Umfeld verantwortlich fühlen.",
    "Eine Beziehung könnte anspruchsvoller werden, wenn Erwartungen unausgesprochen bleiben.",
    "Die Herausforderung wird darin bestehen, sich nach einer Enttäuschung in einer Beziehung nicht vollständig zurückzuziehen.",
    "Sie könnten der Meinung einer Gruppe zu viel Bedeutung beimessen, die Sie in Wirklichkeit kaum kennt.",
    "Eine alte Spannung könnte wieder auftauchen, wenn sie nie wirklich gelöst wurde.",
    "Der Wunsch, Harmonie zu bewahren, könnte Sie dazu bringen, ein Verhalten zu akzeptieren, das Ihnen nicht entspricht.",
    "Bevorzugen Sie Beziehungen, in denen Sie Sie selbst bleiben können, ohne sich ständig rechtfertigen zu müssen.",
    "Sprechen Sie Ihre Grenzen bereits bei den ersten Anzeichen von Unbehagen aus, statt zu warten, bis sich alles ansammelt.",
    "Schenken Sie Ihre Zeit Menschen, die Ihnen ebenso aufrichtige Präsenz bieten, wie Sie selbst geben.",
    "Verwechseln Sie Verfügbarkeit nicht mit dauerhafter Verpflichtung.",
    "Ergreifen Sie die Initiative für ein Gespräch, wenn Sie spüren, dass eine Beziehung es verdient, bewahrt zu werden.",
    "Ziehen Sie sich vorübergehend aus einer sozialen Situation zurück, wenn Ihre Energie zu niedrig wird.",
    "Lassen Sie eine neue Beziehung sich natürlich entwickeln, ohne ihren Platz zu schnell festlegen zu wollen.",
    "Vermeiden Sie es, sofort auf verletzende Worte zu reagieren. Abstand wird Ihnen helfen, eine angemessenere Antwort zu wählen.",
    "Achten Sie bei der Einschätzung der Zuverlässigkeit einer Person ebenso auf Taten wie auf Worte.",
    "Suchen Sie ein Gleichgewicht zwischen Ihrem Bedürfnis nach Nähe und Ihrem Bedürfnis nach Unabhängigkeit.",
    "Dieses Jahr kann Ihr Beziehungsleben bereichern, wenn Sie aufrichtige, ausgeglichene und respektvolle Verbindungen bevorzugen.",
    "Ihr Umfeld wird sich positiv entwickeln, wenn Sie Beziehungen, die Ihren Werten entsprechen, mehr Raum geben.",
    "Die kommenden Monate könnten eine Freundschaft stärken, eine Beziehung klären oder eine wichtige neue Begegnung begünstigen.",
    "Sie könnten das Jahr mit einem klareren Bild davon beenden, auf welche Menschen Sie sich wirklich verlassen können.",
    "Ihr Sozialleben wird an Tiefe gewinnen, je besser Sie Ihre Energie und Ihre Grenzen schützen.",
    "Eine Beziehung könnte durch direkte und wohlwollende Kommunikation stabiler werden.",
    "Dieses Jahr erinnert Sie daran, dass eine gesunde Beziehung ebenso viel Sicherheit wie Freiheit bieten sollte.",
    "Ihre Fähigkeit, Ihr Umfeld mit Bedacht zu wählen, wird Ihr emotionales Gleichgewicht verbessern.",
    "Eine neue Beziehungsdynamik könnte Ihnen mehr Leichtigkeit und Vertrauen bringen.",
    "Wenn Sie Ihren Bedürfnissen treu bleiben, werden Sie authentischere und erfüllendere Begegnungen anziehen.",
],
  it: [
    "La vostra vita sociale potrebbe assumere maggiore importanza quest’anno. Alcuni incontri o conversazioni vi aiuteranno a comprendere meglio il posto che occupate nelle vostre relazioni.",
    "I prossimi mesi pongono l’accento sui vostri scambi, sulle amicizie e sul vostro modo di creare legami. Potreste cercare relazioni più sincere ed equilibrate.",
    "Quest’anno vi invita a osservare la qualità delle persone che vi circondano. Alcune relazioni vi daranno energia, mentre altre potrebbero richiedervene di più.",
    "La vostra cerchia sociale potrebbe vivere un’evoluzione importante. Potrebbe nascere una nuova vicinanza mentre una relazione meno naturale si allontana gradualmente.",
    "Il clima relazionale favorisce conversazioni autentiche e legami costruiti sulla fiducia. Potreste diventare più selettivi nelle vostre frequentazioni.",
    "I prossimi mesi potrebbero aiutarvi a riprendere contatto con una persona importante o ad approfondire una relazione già presente.",
    "Il vostro bisogno di condivisione aumenta, ma soprattutto desidererete essere circondati da persone capaci di rispettare la vostra sensibilità e i vostri limiti.",
    "Inizia un periodo più attivo nella vostra vita sociale. Inviti, scambi e nuove conoscenze potrebbero moltiplicarsi.",
    "Quest’anno vi spinge a trovare un equilibrio migliore tra il bisogno di solitudine e il desiderio di rimanere in contatto con gli altri.",
    "Il vostro modo di entrare in relazione evolve. Potreste cercare meno quantità e più profondità nei vostri scambi.",
    "La vostra presenza sarà apprezzata quando rimarrete naturali, senza cercare di rispondere a tutte le aspettative di chi vi circonda.",
    "Una conversazione spontanea potrebbe portarvi un’idea, un sostegno o una nuova prospettiva.",
    "Potreste sentire il bisogno di rivedere il posto occupato da alcune persone nella vostra vita quotidiana.",
    "L’anno favorisce scambi semplici, onesti e senza inutili sottintesi.",
    "Una relazione potrebbe diventare più fluida quando ciascuno esprimerà chiaramente i propri bisogni.",
    "Potreste essere più sensibili all’atmosfera di alcuni gruppi. Scegliete gli ambienti in cui vi sentite davvero a vostro agio.",
    "La vostra vita sociale guadagnerà qualità quando smetterete di mantenere legami soltanto per abitudine.",
    "Una persona potrebbe mostrarsi più presente del previsto. Prendetevi il tempo di osservare le sue intenzioni senza trarre conclusioni troppo rapidamente.",
    "Le relazioni più solide saranno quelle in cui potrete parlare liberamente senza dovervi adattare continuamente.",
    "Una nuova dinamica potrebbe instaurarsi nel vostro ambiente e modificare alcune abitudini sociali.",
    "Un’amicizia potrebbe rafforzarsi grazie a una conversazione più personale o a un’esperienza importante condivisa durante l’anno.",
    "Potreste riprendere contatto con una persona che non vedete da qualche tempo.",
    "Un’amicizia potrebbe richiedere un chiarimento per evitare che un disagio si stabilizzi nel tempo.",
    "Un amico potrebbe avere bisogno del vostro ascolto. Fate però attenzione a non portare da soli le sue difficoltà.",
    "Potreste scoprire un nuovo lato di una persona che conoscete già.",
    "L’anno favorisce le amicizie fondate sulla lealtà, sul rispetto e sulla reciprocità.",
    "Un invito potrebbe aiutarvi a uscire dalla routine e a incontrare persone interessanti.",
    "Potreste allontanarvi naturalmente da una relazione diventata meno compatibile con la vostra evoluzione attuale.",
    "Un gesto semplice potrebbe ravvivare un’amicizia che credevate indebolita.",
    "Le persone che vi circondano potrebbero ricordarvi l’importanza di chiedere sostegno invece di gestire tutto da soli.",
    "Una situazione familiare potrebbe richiedere maggiore pazienza e comunicazione nel corso dell’anno.",
    "Una conversazione importante potrebbe permettere di chiarire un vecchio malinteso.",
    "Potreste sentire il bisogno di proteggere maggiormente il vostro spazio personale dalle aspettative della famiglia.",
    "Un membro della famiglia potrebbe sorprendervi con il suo sostegno o la sua comprensione.",
    "Una responsabilità familiare potrebbe modificare temporaneamente la vostra organizzazione.",
    "L’anno vi invita a evitare reazioni automatiche in una relazione carica di vecchie emozioni.",
    "Un avvicinamento potrebbe diventare possibile se tutti accetteranno di parlare con maggiore sincerità.",
    "Potreste dover ribadire un limite che non è stato sufficientemente rispettato.",
    "Un’attività o un evento condiviso potrebbe migliorare l’atmosfera familiare.",
    "La vostra calma vi aiuterà a non amplificare una tensione che potrebbe risolversi più facilmente del previsto.",
    "Un nuovo incontro potrebbe aprirvi a un mondo, un’idea o un’attività diversa.",
    "Potreste conoscere una persona con cui la conversazione sembrerà subito naturale.",
    "Un contesto professionale, sociale o digitale potrebbe favorire una nuova relazione interessante.",
    "Un incontro discreto potrebbe diventare più importante con il tempo. Non affidatevi soltanto alla prima impressione.",
    "L’anno favorisce i legami creati attorno a un interesse, un progetto o un valore comune.",
    "Potreste attirare persone che riflettono la vostra evoluzione recente.",
    "Una nuova conoscenza potrebbe aiutarvi a superare un modo di pensare diventato troppo limitato.",
    "Una relazione potrebbe iniziare lentamente, ma acquisire progressivamente fiducia e profondità.",
    "Potreste essere presentati a una persona capace di svolgere un ruolo utile in un progetto futuro.",
    "Un incontro inatteso potrebbe riaccendere la vostra voglia di partecipare maggiormente alla vita sociale.",
    "I vostri scambi diventeranno più fluidi se esprimerete direttamente ciò che sentite o vi aspettate.",
    "Evitate di dare per scontato che gli altri comprendano automaticamente le vostre intenzioni.",
    "Una formulazione più delicata vi permetterà di trasmettere un messaggio importante senza diminuirne la chiarezza.",
    "Potreste dover correggere un’informazione o chiarire parole interpretate male.",
    "La vostra capacità di ascolto avrà un ruolo importante quanto le vostre parole in una conversazione delicata.",
    "Una conversazione rimandata merita forse di avvenire prima che il disagio aumenti.",
    "Potreste scoprire che una persona condivide il vostro punto di vista più di quanto pensavate.",
    "L’anno favorisce scambi onesti, ma sarà importante evitare parole pronunciate sotto l’impulso dell’impazienza.",
    "Un messaggio, una telefonata o una conversazione potrebbe modificare positivamente la vostra percezione di una relazione.",
    "La vostra capacità di porre le domande giuste vi aiuterà a comprendere meglio le motivazioni di una persona.",
    "L’inizio dell’anno favorirà una selezione nelle vostre relazioni e il chiarimento di alcune aspettative.",
    "La primavera potrebbe portare più inviti, incontri e scambi spontanei.",
    "La metà dell’anno favorirà gli avvicinamenti, i progetti condivisi e le nuove collaborazioni.",
    "L’estate potrebbe rendere la vostra vita sociale più attiva e aiutarvi a uscire da alcune abitudini.",
    "L’inizio dell’autunno sarà favorevole alle conversazioni importanti e ai chiarimenti costruttivi.",
    "La fine dell’anno favorirà le riunioni, i bilanci relazionali e i legami più sinceri.",
    "Un periodo più tranquillo vi permetterà di comprendere meglio quali relazioni meritano la vostra energia.",
    "La seconda metà dell’anno potrebbe portare un incontro capace di assumere progressivamente un ruolo importante.",
    "Alcune relazioni evolveranno rapidamente, mentre altre richiederanno più tempo e pazienza.",
    "I periodi più favorevoli saranno quelli in cui accetterete di rimanere voi stessi senza cercare di accontentare tutti.",
    "La sfida principale sarà non esaurirvi nel mantenere relazioni che non sono più reciproche.",
    "Potreste avere la tendenza ad accettare un invito o una richiesta quando in realtà avete bisogno di riposo.",
    "Un’osservazione potrebbe toccarvi più del previsto. Prendetevi il tempo di verificare la vera intenzione prima di reagire.",
    "Il bisogno di evitare un conflitto potrebbe spingervi a tacere un limite che invece è importante.",
    "Potreste sentirvi responsabili dell’umore o del benessere di una persona che vi circonda.",
    "Una relazione potrebbe diventare più esigente se le aspettative rimangono implicite.",
    "La sfida consisterà nel non isolarvi completamente dopo una delusione relazionale.",
    "Potreste attribuire troppa importanza all’opinione di un gruppo che in realtà non vi conosce davvero.",
    "Una vecchia tensione potrebbe riemergere se non è mai stata realmente risolta.",
    "Il desiderio di preservare l’armonia potrebbe portarvi ad accettare un comportamento che non vi conviene.",
    "Privilegiate le relazioni in cui potete rimanere voi stessi senza dovervi giustificare continuamente.",
    "Esprimete i vostri limiti ai primi segnali di disagio invece di aspettare che tutto si accumuli.",
    "Dedicate il vostro tempo alle persone che vi offrono una presenza sincera quanto la vostra.",
    "Non confondete la disponibilità con un obbligo permanente.",
    "Prendete l’iniziativa di una conversazione quando sentite che una relazione merita di essere preservata.",
    "Allontanatevi temporaneamente da una situazione sociale quando la vostra energia diventa troppo bassa.",
    "Lasciate che una nuova relazione evolva naturalmente senza cercare di definirne troppo rapidamente il posto.",
    "Evitate di rispondere immediatamente a parole che vi feriscono. Prendere le distanze vi aiuterà a scegliere una risposta più giusta.",
    "Prestate attenzione ai fatti tanto quanto alle parole quando valutate l’affidabilità di una persona.",
    "Cercate un equilibrio tra il vostro bisogno di vicinanza e il vostro bisogno di indipendenza.",
    "Quest’anno può arricchire la vostra vita relazionale se privilegerete legami sinceri, equilibrati e rispettosi.",
    "Il vostro ambiente evolverà positivamente quando darete più spazio alle relazioni che corrispondono ai vostri valori.",
    "I prossimi mesi potrebbero rafforzare un’amicizia, chiarire una relazione o favorire un nuovo incontro importante.",
    "Potreste terminare l’anno con una visione più chiara delle persone su cui potete davvero contare.",
    "La vostra vita sociale acquisterà profondità man mano che proteggerete meglio la vostra energia e i vostri limiti.",
    "Una relazione potrebbe diventare più solida grazie a una comunicazione diretta e benevola.",
    "Quest’anno vi ricorda che una relazione sana deve offrire tanta sicurezza quanto libertà.",
    "La vostra capacità di scegliere con discernimento le persone che vi circondano migliorerà il vostro equilibrio emotivo.",
    "Una nuova dinamica relazionale potrebbe portarvi maggiore leggerezza e fiducia.",
    "Rimanendo fedeli ai vostri bisogni, attirerete scambi più autentici e soddisfacenti.",
],
  pt: [
    "Sua vida social poderá ganhar mais importância neste ano. Alguns encontros ou conversas ajudarão você a compreender melhor o lugar que ocupa em seus relacionamentos.",
    "Os próximos meses destacam suas trocas, amizades e sua maneira de criar vínculos. Você poderá buscar relações mais sinceras e equilibradas.",
    "Este ano convida você a observar a qualidade das pessoas ao seu redor. Algumas relações trarão energia, enquanto outras poderão exigir mais de você.",
    "Seu círculo social poderá passar por uma evolução importante. Uma nova proximidade poderá surgir enquanto uma relação menos natural se afasta gradualmente.",
    "O clima relacional favorece conversas autênticas e vínculos construídos com base na confiança. Você poderá se tornar mais seletivo em suas relações.",
    "Os próximos meses poderão ajudar você a retomar o contato com uma pessoa importante ou a aprofundar uma relação já existente.",
    "Sua necessidade de compartilhar aumenta, mas principalmente você desejará estar cercado de pessoas capazes de respeitar sua sensibilidade e seus limites.",
    "Começa um período mais ativo em sua vida social. Convites, conversas e novas amizades poderão se multiplicar.",
    "Este ano incentiva você a encontrar um equilíbrio melhor entre sua necessidade de ficar sozinho e sua vontade de permanecer conectado aos outros.",
    "Sua maneira de se relacionar está evoluindo. Você poderá buscar menos quantidade e mais profundidade em suas trocas.",
    "Sua presença será apreciada quando você agir de forma natural, sem tentar atender a todas as expectativas das pessoas ao seu redor.",
    "Uma conversa espontânea poderá trazer uma ideia, apoio ou uma nova perspectiva.",
    "Você poderá sentir a necessidade de rever o espaço ocupado por certas pessoas em sua vida cotidiana.",
    "O ano favorece conversas simples, honestas e sem indiretas desnecessárias.",
    "Uma relação poderá se tornar mais fluida quando cada pessoa expressar claramente suas necessidades.",
    "Você poderá ficar mais sensível ao ambiente de certos grupos. Escolha os lugares em que realmente se sente à vontade.",
    "Sua vida social ganhará qualidade quando você deixar de manter vínculos apenas por hábito.",
    "Uma pessoa poderá se mostrar mais presente do que o esperado. Reserve um tempo para observar suas intenções sem tirar conclusões rápidas demais.",
    "As relações mais sólidas serão aquelas em que você poderá falar livremente sem precisar se adaptar o tempo todo.",
    "Uma nova dinâmica poderá surgir em seu círculo social e modificar alguns hábitos.",
    "Uma amizade poderá se fortalecer graças a uma conversa mais pessoal ou a uma experiência importante compartilhada ao longo do ano.",
    "Você poderá retomar o contato com uma pessoa que não vê há algum tempo.",
    "Uma amizade poderá precisar de um esclarecimento para evitar que um desconforto se torne duradouro.",
    "Um amigo poderá precisar da sua escuta. No entanto, tome cuidado para não carregar sozinho as dificuldades dele.",
    "Você poderá descobrir um novo lado de uma pessoa que já conhece.",
    "O ano favorece amizades baseadas em lealdade, respeito e reciprocidade.",
    "Um convite poderá ajudar você a sair da rotina e conhecer pessoas interessantes.",
    "Você poderá se afastar naturalmente de uma relação que se tornou menos compatível com sua evolução atual.",
    "Um gesto simples poderá reavivar uma amizade que você acreditava ter enfraquecido.",
    "As pessoas ao seu redor poderão lembrar você da importância de pedir apoio em vez de tentar resolver tudo sozinho.",
    "Uma situação familiar poderá exigir mais paciência e comunicação ao longo do ano.",
    "Uma conversa importante poderá ajudar a esclarecer um antigo mal-entendido.",
    "Você poderá sentir a necessidade de proteger mais seu espaço pessoal diante das expectativas da família.",
    "Um membro da família poderá surpreender você com seu apoio ou compreensão.",
    "Uma responsabilidade familiar poderá modificar temporariamente sua organização.",
    "O ano convida você a evitar reações automáticas em uma relação carregada de emoções antigas.",
    "Uma aproximação poderá se tornar possível se todos aceitarem conversar com mais sinceridade.",
    "Você poderá precisar reafirmar um limite que não foi suficientemente respeitado.",
    "Uma atividade ou um evento compartilhado poderá melhorar o ambiente familiar.",
    "Sua calma ajudará você a não ampliar uma tensão que poderá ser resolvida de maneira mais simples do que o esperado.",
    "Um novo encontro poderá apresentar a você um universo, uma ideia ou uma atividade diferente.",
    "Você poderá conhecer uma pessoa com quem a conversa parecerá imediatamente natural.",
    "Um contexto profissional, social ou digital poderá favorecer uma nova relação interessante.",
    "Um encontro discreto poderá se tornar mais importante com o tempo. Não confie apenas na primeira impressão.",
    "O ano favorece vínculos criados em torno de um interesse, projeto ou valor em comum.",
    "Você poderá atrair pessoas que refletem sua evolução recente.",
    "Uma nova amizade poderá ajudar você a sair de uma maneira de pensar que se tornou limitada demais.",
    "Uma relação poderá começar devagar, mas ganhar gradualmente confiança e profundidade.",
    "Você poderá ser apresentado a uma pessoa capaz de desempenhar um papel útil em um projeto futuro.",
    "Um encontro inesperado poderá renovar sua vontade de participar mais ativamente da vida social.",
    "Suas conversas ficarão mais fluidas se você expressar diretamente o que sente ou espera.",
    "Evite presumir que os outros compreendem automaticamente suas intenções.",
    "Uma formulação mais delicada permitirá que você transmita uma mensagem importante sem perder a clareza.",
    "Você poderá precisar corrigir uma informação ou esclarecer uma fala que foi mal interpretada.",
    "Sua capacidade de ouvir terá um papel tão importante quanto suas palavras em uma conversa delicada.",
    "Uma conversa adiada talvez precise acontecer antes que o desconforto aumente ainda mais.",
    "Você poderá descobrir que uma pessoa compartilha mais do seu ponto de vista do que imaginava.",
    "O ano favorece conversas honestas, mas será importante evitar palavras ditas no calor da impaciência.",
    "Uma mensagem, ligação ou conversa poderá mudar positivamente sua percepção de uma relação.",
    "Sua capacidade de fazer as perguntas certas ajudará você a compreender melhor as motivações de uma pessoa.",
    "O início do ano favorecerá uma seleção em suas relações e o esclarecimento de certas expectativas.",
    "A primavera poderá trazer mais convites, encontros e conversas espontâneas.",
    "A metade do ano favorecerá aproximações, projetos compartilhados e novas colaborações.",
    "O verão poderá tornar sua vida social mais ativa e ajudar você a sair de alguns hábitos.",
    "O início do outono será favorável a conversas importantes e esclarecimentos construtivos.",
    "O final do ano favorecerá reencontros, avaliações dos relacionamentos e os vínculos mais sinceros.",
    "Um período mais tranquilo permitirá que você compreenda melhor quais relações merecem sua energia.",
    "O segundo semestre poderá trazer um encontro capaz de ocupar gradualmente um lugar importante.",
    "Algumas relações evoluirão rapidamente, enquanto outras exigirão mais tempo e paciência.",
    "Os períodos mais favoráveis serão aqueles em que você aceitar ser você mesmo sem tentar agradar a todos.",
    "O principal desafio será não se esgotar tentando manter relações que deixaram de ser recíprocas.",
    "Você poderá ter a tendência de aceitar um convite ou pedido quando, na verdade, precisa descansar.",
    "Um comentário poderá afetar você mais do que o esperado. Reserve um tempo para verificar a verdadeira intenção antes de reagir.",
    "A necessidade de evitar um conflito poderá levar você a silenciar um limite que, na verdade, é importante.",
    "Você poderá se sentir responsável pelo humor ou pelo bem-estar de uma pessoa próxima.",
    "Uma relação poderá se tornar mais exigente se as expectativas continuarem implícitas.",
    "O desafio será não se isolar completamente depois de uma decepção em uma relação.",
    "Você poderá dar importância demais à opinião de um grupo que, na realidade, não conhece você de verdade.",
    "Uma antiga tensão poderá reaparecer se nunca tiver sido realmente resolvida.",
    "O desejo de preservar a harmonia poderá levar você a aceitar um comportamento que não lhe faz bem.",
    "Priorize relações nas quais você possa ser você mesmo sem precisar se justificar o tempo todo.",
    "Expresse seus limites aos primeiros sinais de desconforto em vez de esperar que tudo se acumule.",
    "Dedique seu tempo às pessoas que oferecem a você uma presença tão sincera quanto a sua.",
    "Não confunda disponibilidade com obrigação permanente.",
    "Tome a iniciativa de conversar quando sentir que uma relação merece ser preservada.",
    "Afaste-se temporariamente de uma situação social quando sua energia estiver muito baixa.",
    "Deixe uma nova relação evoluir naturalmente sem tentar definir rápido demais o lugar dela.",
    "Evite responder imediatamente a palavras que machucam você. Tomar distância ajudará a escolher uma resposta mais justa.",
    "Observe as atitudes tanto quanto as palavras ao avaliar a confiabilidade de uma pessoa.",
    "Busque um equilíbrio entre sua necessidade de proximidade e sua necessidade de independência.",
    "Este ano poderá enriquecer sua vida relacional se você priorizar vínculos sinceros, equilibrados e respeitosos.",
    "Seu círculo social evoluirá de forma positiva quando você abrir mais espaço para relações alinhadas aos seus valores.",
    "Os próximos meses poderão fortalecer uma amizade, esclarecer uma relação ou favorecer um novo encontro importante.",
    "Você poderá terminar o ano com uma visão mais clara das pessoas com quem realmente pode contar.",
    "Sua vida social ganhará profundidade à medida que você proteger melhor sua energia e seus limites.",
    "Uma relação poderá se tornar mais sólida graças a uma comunicação direta e gentil.",
    "Este ano lembra você de que uma relação saudável deve oferecer tanta segurança quanto liberdade.",
    "Sua capacidade de escolher as pessoas ao seu redor com discernimento melhorará seu equilíbrio emocional.",
    "Uma nova dinâmica relacional poderá trazer mais leveza e confiança.",
    "Ao permanecer fiel às suas necessidades, você atrairá trocas mais autênticas e satisfatórias.",
],
};
/* =========================================================
   TRANSLATION MAPS
========================================================= */
const SOCIAL_TITLES = Object.fromEntries(
  (["en", "es", "de", "it", "pt"] as const).map(
    (locale) => [
      locale,
      buildTranslationMap(
        SOCIAL_TITLES_FR,
        SOCIAL_TITLES_TRANSLATIONS[locale],
      ),
    ],
  ),
) as Record<
  Exclude<PaidPdfLocale, "fr">,
  TranslationMap
>;
const SOCIAL_TEXTS = Object.fromEntries(
  (["en", "es", "de", "it", "pt"] as const).map(
    (locale) => [
      locale,
      buildTranslationMap(
        SOCIAL_TEXTS_FR,
        SOCIAL_TEXTS_TRANSLATIONS[locale],
      ),
    ],
  ),
) as Record<
  Exclude<PaidPdfLocale, "fr">,
  TranslationMap
>;
/* =========================================================
   LOCALIZER — YEAR HOROSCOPE SOCIAL
========================================================= */
export function localizeYearHoroscopeSocial(
  source: string,
  locale: PaidPdfLocale,
): string {
  if (locale === "fr") {
    return source;
  }

  let output = source;

  output = applyTranslations(
    output,
    SOCIAL_TITLES[locale],
  );

  output = applyTranslations(
    output,
    SOCIAL_TEXTS[locale],
  );

  return output;
}
