import type {
  PaidPdfLocale,
} from "./premium-localization";

type TranslationMap = Record<string, string>;

function buildTranslationMap(
  french: readonly string[],
  translated: readonly string[],
): TranslationMap {
  if (french.length !== translated.length) {
    throw new Error(
      `Translation length mismatch: ${french.length} French entries vs ${translated.length} translated entries`,
    );
  }

  return Object.fromEntries(
    french.map((text, index) => [text, translated[index]]),
  );
}

function applyTranslations(
  source: string,
  translations: TranslationMap,
): string {
  let output = source;

  for (const [from, to] of Object.entries(translations)) {
    output = output.split(from).join(to);
  }

  return output;
}

const TRANSIT_TITLES_FR = [
  "Les grands transits planétaires de votre année",
  "Les influences célestes qui guideront votre année",
  "Le climat planétaire de votre année",
  "Une année façonnée par les mouvements du ciel",
  "Les planètes qui marqueront votre évolution",
  "Les grandes influences astrologiques de l’année",
  "Votre année au rythme des planètes",
  "Les mouvements célestes de votre année",
] as const;

const PLANET_LABELS_FR = [
  "Soleil",
  "Mercure",
  "Vénus",
  "Mars",
  "Jupiter",
  "Saturne",
  "Planètes lentes",
] as const;

const TRANSIT_TEXTS_FR = [
  "Les mouvements planétaires de cette année créent une période d’évolution, de réflexion et d’ajustement. Certaines influences agiront rapidement, tandis que d’autres transformeront progressivement votre manière d’avancer.",
  "Le ciel de l’année met en lumière plusieurs domaines de votre vie. Les transits planétaires vous invitent à observer ce qui évolue, ce qui résiste et ce qui demande une nouvelle direction.",
  "Les influences planétaires des prochains mois pourraient modifier votre rythme, vos priorités et votre perception de certaines situations.",
  "Cette année est marquée par des énergies complémentaires : certaines vous pousseront à agir, tandis que d’autres vous demanderont de ralentir et de réfléchir.",
  "Les transits de l’année favorisent une meilleure compréhension de vos désirs, de vos limites et des changements que vous êtes prêt à entreprendre.",
  "Le climat planétaire vous accompagne dans une période d’évolution durable. Une situation ancienne pourrait être abordée avec davantage de maturité.",
  "Les prochains mois seront influencés par plusieurs mouvements célestes capables d’accentuer votre intuition, votre motivation ou votre besoin de changement.",
  "Cette année vous invite à suivre les mouvements du ciel sans chercher à contrôler chaque résultat. Certaines réponses apparaîtront progressivement.",
  "Les transits planétaires pourraient révéler une occasion de croissance personnelle, relationnelle ou professionnelle.",
  "Le ciel de l’année vous encourage à avancer avec souplesse. Les changements les plus utiles pourraient d’abord sembler inconfortables.",
  "Le Soleil renforce votre besoin d’affirmer vos priorités et de concentrer votre énergie sur ce qui compte réellement.",
  "Le passage du Soleil apporte davantage de visibilité à un projet ou une décision importante.",
  "L’énergie solaire vous encourage à reprendre pleinement votre place.",
  "Le Soleil met en lumière une situation que vous ne pourrez plus ignorer.",
  "Cette influence favorise la confiance, l’initiative et l’affirmation personnelle.",
  "Le Soleil vous pousse à reconnaître ce qui vous motive profondément.",
  "Une période de renouvellement commence sous cette influence.",
  "Le Soleil favorise les démarches où vous devez assumer davantage de responsabilités.",
  "Cette influence vous aide à clarifier la direction que vous souhaitez donner à votre année.",
  "Le passage solaire pourrait raviver votre ambition et votre créativité.",
  "Mercure favorise les discussions importantes, les apprentissages et les décisions réfléchies.",
  "Une conversation pourrait clarifier une situation restée ambiguë depuis longtemps.",
  "Mercure vous invite à vérifier les informations avant toute décision importante.",
  "Les échanges seront nombreux, mais les détails demanderont davantage d'attention.",
  "Cette influence soutient les projets d’écriture, de communication et de négociation.",
  "Une information inattendue pourrait modifier votre vision d'un projet.",
  "Mercure vous encourage à poser les bonnes questions.",
  "Votre esprit sera particulièrement actif durant plusieurs périodes de l'année.",
  "Les décisions rationnelles seront favorisées sans négliger votre intuition.",
  "Un déplacement ou une rencontre pourrait influencer durablement votre évolution.",
  "Vénus adoucit le climat relationnel et favorise les rapprochements.",
  "Vous pourriez rechercher davantage d’harmonie dans vos relations.",
  "Vénus met en lumière votre besoin d’affection et de reconnaissance.",
  "Cette influence favorise les conversations sincères et les réconciliations.",
  "Vénus pourrait transformer votre rapport à l’amour, à l’argent ou à votre estime personnelle.",
  "Une rencontre pourrait prendre une importance inattendue.",
  "La créativité et les plaisirs simples seront davantage valorisés.",
  "Vous pourriez ressentir un besoin plus fort de stabilité affective.",
  "Vénus rappelle que l’harmonie ne doit jamais se construire au détriment de vos limites.",
  "Cette influence renforcera progressivement votre confiance.",
  "Mars augmente votre motivation et votre désir d’agir.",
  "Une situation pourrait demander davantage de courage et de détermination.",
  "Mars vous pousse à transformer vos intentions en actions concrètes.",
  "Cette influence pourrait accentuer votre impatience si vous manquez de préparation.",
  "Les projets exigeant énergie et persévérance seront favorisés.",
  "Vous pourriez ressentir un besoin accru d’indépendance.",
  "Mars vous encourage à défendre vos besoins avec assurance.",
  "Une énergie nouvelle pourrait relancer un projet ancien.",
  "Une meilleure gestion de votre impulsivité deviendra essentielle.",
  "Mars pourrait vous donner l’élan nécessaire pour franchir une étape importante.",
  "Jupiter favorise l’expansion, l’apprentissage et les nouvelles possibilités.",
  "Une situation pourrait évoluer plus favorablement que prévu.",
  "Jupiter vous encourage à penser plus grand tout en restant réaliste.",
  "Une occasion de croissance pourrait transformer votre trajectoire.",
  "Les voyages, études et nouveaux projets seront favorisés.",
  "Cette influence renforcera progressivement votre confiance.",
  "Une personne expérimentée pourrait jouer un rôle important.",
  "Les projets à long terme bénéficieront d’un soutien particulier.",
  "Une porte pourrait s’ouvrir si vous acceptez de sortir de votre zone de confort.",
  "Jupiter vous invite à reconnaître les occasions sans les idéaliser.",
  "Saturne demande davantage de discipline et de constance.",
  "Une responsabilité importante pourrait devenir plus exigeante mais aussi plus constructive.",
  "Cette influence vous invite à consolider vos bases avant d'accélérer.",
  "Un ralentissement apparent pourrait préparer une réussite plus solide.",
  "Les résultats durables demanderont patience et persévérance.",
  "Une limite deviendra plus visible afin de favoriser une meilleure organisation.",
  "Les engagements sérieux seront particulièrement favorisés.",
  "Certaines contraintes prépareront votre réussite future.",
  "Saturne vous encourage à protéger votre énergie avec davantage de discernement.",
  "Une difficulté persistante pourrait finalement devenir une force.",
  "Les planètes lentes travaillent en profondeur et transformeront progressivement votre évolution.",
  "Uranus, Neptune et Pluton accentuent un changement déjà amorcé.",
  "Une influence subtile modifiera votre intuition et votre perception.",
  "Ces planètes vous invitent à abandonner progressivement certaines habitudes.",
  "Uranus favorisera les surprises tandis que Neptune demandera davantage de discernement.",
  "Pluton accompagnera une profonde transformation intérieure.",
  "Ces influences produisent leurs effets sur plusieurs mois.",
  "Une ancienne manière de fonctionner pourrait progressivement disparaître.",
  "Les changements les plus profonds seront souvent les plus discrets.",
  "Une prise de conscience pourrait devenir le point de départ d'une nouvelle étape de vie.",
  "L’influence dominante de l’année vous pousse à trouver un meilleur équilibre entre action et réflexion.",
  "Le thème central concerne votre capacité à avancer sans perdre votre stabilité intérieure.",
  "L’énergie dominante favorise les décisions réfléchies et les ajustements durables.",
  "Cette année met particulièrement l’accent sur la confiance et la communication.",
  "La principale influence planétaire vous invite à transformer une hésitation en décision.",
  "L’énergie générale pourrait vous aider à sortir d’une longue période d’attente.",
  "Le climat astrologique favorise une évolution progressive plutôt qu’un bouleversement brutal.",
  "Votre principale leçon sera d’agir au bon moment.",
  "Le ciel vous encourage à reconnaître les ouvertures tout en restant attentif aux détails.",
  "Cette influence dominante vous aidera à clarifier vos véritables priorités.",
  "Observez les changements de rythme sans chercher à résister automatiquement.",
  "Utilisez les périodes dynamiques pour agir et les périodes plus lentes pour préparer la suite.",
  "Ne prenez pas une émotion passagère pour une vérité définitive.",
  "Restez attentif aux rencontres et aux informations importantes.",
  "Accordez-vous du temps lorsque plusieurs influences semblent contradictoires.",
  "Certaines évolutions auront besoin de plusieurs mois avant de révéler tout leur sens.",
  "Appuyez-vous sur les faits tout en laissant une place raisonnable à votre intuition.",
  "Profitez de l’élan planétaire pour avancer sur une priorité essentielle.",
  "Acceptez de revoir une stratégie si les circonstances évoluent.",
  "Considérez les transits comme des guides plutôt que comme des certitudes absolues.",
  "Les transits de cette année peuvent vous aider à avancer avec davantage de conscience, de souplesse et de confiance.",
  "Le ciel vous accompagne dans une période d’évolution capable de produire des effets durables.",
  "Vous pourriez terminer l’année avec une vision beaucoup plus claire de votre avenir.",
  "Les influences planétaires rappellent que chaque période possède son propre rythme.",
  "Une évolution importante pourrait commencer discrètement avant de devenir évidente.",
  "Cette année vous offre l’occasion d’utiliser les mouvements du ciel comme un véritable soutien.",
  "Les transits favoriseront votre progression si vous restez attentif sans perdre votre discernement.",
  "Une meilleure compréhension des énergies planétaires facilitera vos décisions importantes.",
  "Le ciel vous invite à accueillir le changement sans renoncer à votre stabilité intérieure.",
  "En avançant avec patience et lucidité, vous pourrez transformer ces influences en véritable croissance personnelle.",
] as const;

const TRANSIT_TITLES_TRANSLATIONS: Record<Exclude<PaidPdfLocale, "fr">, readonly string[]> = {
  en: [
    "The major planetary transits of your year",
    "The celestial influences that will guide your year",
    "The planetary climate of your year",
    "A year shaped by the movements of the sky",
    "The planets that will mark your evolution",
    "The major astrological influences of the year",
    "Your year to the rhythm of the planets",
    "The celestial movements of your year",
],
  es: [
    "Los grandes tránsitos planetarios de tu año",
    "Las influencias celestes que guiarán tu año",
    "El clima planetario de tu año",
    "Un año marcado por los movimientos del cielo",
    "Los planetas que marcarán tu evolución",
    "Las grandes influencias astrológicas del año",
    "Tu año al ritmo de los planetas",
    "Los movimientos celestes de tu año",
],
  de: [
    "Die großen planetarischen Transite Ihres Jahres",
    "Die himmlischen Einflüsse, die Ihr Jahr begleiten werden",
    "Das planetarische Klima Ihres Jahres",
    "Ein Jahr, geprägt von den Bewegungen des Himmels",
    "Die Planeten, die Ihre Entwicklung prägen werden",
    "Die großen astrologischen Einflüsse des Jahres",
    "Ihr Jahr im Rhythmus der Planeten",
    "Die Himmelsbewegungen Ihres Jahres",
],
  it: [
    "I grandi transiti planetari del vostro anno",
    "Le influenze celesti che guideranno il vostro anno",
    "Il clima planetario del vostro anno",
    "Un anno plasmato dai movimenti del cielo",
    "I pianeti che segneranno la vostra evoluzione",
    "Le grandi influenze astrologiche dell’anno",
    "Il vostro anno al ritmo dei pianeti",
    "I movimenti celesti del vostro anno",
],
  pt: [
    "Os grandes trânsitos planetários do seu ano",
    "As influências celestes que guiarão o seu ano",
    "O clima planetário do seu ano",
    "Um ano moldado pelos movimentos do céu",
    "Os planetas que marcarão sua evolução",
    "As grandes influências astrológicas do ano",
    "Seu ano no ritmo dos planetas",
    "Os movimentos celestes do seu ano",
],
};

const PLANET_LABELS_TRANSLATIONS: Record<Exclude<PaidPdfLocale, "fr">, readonly string[]> = {
  en: [
    "Sun",
    "Mercury",
    "Venus",
    "Mars",
    "Jupiter",
    "Saturn",
    "Outer planets",
],
  es: [
    "Sol",
    "Mercurio",
    "Venus",
    "Marte",
    "Júpiter",
    "Saturno",
    "Planetas lentos",
],
  de: [
    "Sonne",
    "Merkur",
    "Venus",
    "Mars",
    "Jupiter",
    "Saturn",
    "Langsamlaufende Planeten",
],
  it: [
    "Sole",
    "Mercurio",
    "Venere",
    "Marte",
    "Giove",
    "Saturno",
    "Pianeti lenti",
],
  pt: [
    "Sol",
    "Mercúrio",
    "Vênus",
    "Marte",
    "Júpiter",
    "Saturno",
    "Planetas lentos",
],
};

const TRANSIT_TEXTS_TRANSLATIONS: Record<Exclude<PaidPdfLocale, "fr">, readonly string[]> = {
  en: [
    "The planetary movements of this year create a period of growth, reflection, and adjustment. Some influences will act quickly, while others will gradually transform the way you move forward.",
    "The sky this year highlights several areas of your life. Planetary transits invite you to observe what is evolving, what is resisting, and what needs a new direction.",
    "The planetary influences of the coming months could change your pace, priorities, and perception of certain situations.",
    "This year is marked by complementary energies: some will push you to act, while others will ask you to slow down and reflect.",
    "This year’s transits encourage a better understanding of your desires, your limits, and the changes you are ready to undertake.",
    "The planetary climate accompanies you through a period of lasting growth. An old situation could be approached with greater maturity.",
    "The coming months will be influenced by several celestial movements capable of heightening your intuition, motivation, or need for change.",
    "This year invites you to follow the movements of the sky without trying to control every outcome. Some answers will appear gradually.",
    "Planetary transits could reveal an opportunity for personal, relational, or professional growth.",
    "The sky this year encourages you to move forward with flexibility. The most useful changes may initially feel uncomfortable.",
    "The Sun strengthens your need to affirm your priorities and focus your energy on what truly matters.",
    "The Sun’s passage brings greater visibility to an important project or decision.",
    "Solar energy encourages you to fully reclaim your place.",
    "The Sun highlights a situation you can no longer ignore.",
    "This influence supports confidence, initiative, and self-assertion.",
    "The Sun pushes you to recognize what deeply motivates you.",
    "A period of renewal begins under this influence.",
    "The Sun favors situations in which you need to take on greater responsibility.",
    "This influence helps you clarify the direction you want to give your year.",
    "The Sun’s passage could rekindle your ambition and creativity.",
    "Mercury favors important discussions, learning, and thoughtful decisions.",
    "A conversation could clarify a situation that has remained ambiguous for a long time.",
    "Mercury invites you to verify information before making any important decision.",
    "There will be many exchanges, but details will require greater attention.",
    "This influence supports writing, communication, and negotiation projects.",
    "Unexpected information could change your view of a project.",
    "Mercury encourages you to ask the right questions.",
    "Your mind will be particularly active during several periods of the year.",
    "Rational decisions will be favored without neglecting your intuition.",
    "A trip or encounter could have a lasting influence on your development.",
    "Venus softens the relational climate and favors closer connections.",
    "You may seek greater harmony in your relationships.",
    "Venus highlights your need for affection and recognition.",
    "This influence favors sincere conversations and reconciliations.",
    "Venus could transform your relationship with love, money, or self-esteem.",
    "An encounter could take on unexpected importance.",
    "Creativity and simple pleasures will be valued more highly.",
    "You may feel a stronger need for emotional stability.",
    "Venus reminds you that harmony should never be built at the expense of your boundaries.",
    "This influence will gradually strengthen your confidence.",
    "Mars increases your motivation and desire to act.",
    "A situation could require greater courage and determination.",
    "Mars pushes you to turn your intentions into concrete actions.",
    "This influence could heighten your impatience if you lack preparation.",
    "Projects requiring energy and perseverance will be favored.",
    "You may feel a stronger need for independence.",
    "Mars encourages you to defend your needs with confidence.",
    "New energy could revive an old project.",
    "Better management of your impulsiveness will become essential.",
    "Mars could give you the momentum needed to cross an important threshold.",
    "Jupiter favors expansion, learning, and new possibilities.",
    "A situation could develop more favorably than expected.",
    "Jupiter encourages you to think bigger while remaining realistic.",
    "An opportunity for growth could transform your path.",
    "Travel, studies, and new projects will be favored.",
    "This influence will gradually strengthen your confidence.",
    "An experienced person could play an important role.",
    "Long-term projects will benefit from special support.",
    "A door could open if you agree to step outside your comfort zone.",
    "Jupiter invites you to recognize opportunities without idealizing them.",
    "Saturn calls for greater discipline and consistency.",
    "An important responsibility could become more demanding but also more constructive.",
    "This influence invites you to strengthen your foundations before accelerating.",
    "An apparent slowdown could prepare a more solid success.",
    "Lasting results will require patience and perseverance.",
    "A limitation will become more visible in order to support better organization.",
    "Serious commitments will be particularly favored.",
    "Certain constraints will prepare your future success.",
    "Saturn encourages you to protect your energy with greater discernment.",
    "A persistent difficulty could eventually become a strength.",
    "The outer planets work at a deep level and will gradually transform your development.",
    "Uranus, Neptune, and Pluto intensify a change that has already begun.",
    "A subtle influence will modify your intuition and perception.",
    "These planets invite you to gradually let go of certain habits.",
    "Uranus will favor surprises, while Neptune will require greater discernment.",
    "Pluto will accompany a profound inner transformation.",
    "These influences produce their effects over several months.",
    "An old way of functioning could gradually disappear.",
    "The deepest changes will often be the most discreet.",
    "A realization could become the starting point of a new stage of life.",
    "The dominant influence of the year pushes you to find a better balance between action and reflection.",
    "The central theme concerns your ability to move forward without losing your inner stability.",
    "The dominant energy favors thoughtful decisions and lasting adjustments.",
    "This year places particular emphasis on confidence and communication.",
    "The main planetary influence invites you to transform hesitation into decision.",
    "The overall energy could help you emerge from a long period of waiting.",
    "The astrological climate favors gradual development rather than sudden upheaval.",
    "Your main lesson will be to act at the right moment.",
    "The sky encourages you to recognize openings while remaining attentive to details.",
    "This dominant influence will help you clarify your true priorities.",
    "Observe changes in pace without automatically trying to resist them.",
    "Use dynamic periods to act and slower periods to prepare what comes next.",
    "Do not mistake a passing emotion for a definitive truth.",
    "Stay attentive to encounters and important information.",
    "Give yourself time when several influences seem contradictory.",
    "Some developments will need several months before revealing their full meaning.",
    "Rely on facts while leaving reasonable room for your intuition.",
    "Use the planetary momentum to move forward on an essential priority.",
    "Be willing to review a strategy if circumstances change.",
    "Consider transits as guides rather than absolute certainties.",
    "This year’s transits can help you move forward with greater awareness, flexibility, and confidence.",
    "The sky accompanies you through a period of growth capable of producing lasting effects.",
    "You could end the year with a much clearer vision of your future.",
    "Planetary influences remind you that each period has its own rhythm.",
    "An important development could begin quietly before becoming obvious.",
    "This year gives you the opportunity to use the movements of the sky as genuine support.",
    "Transits will support your progress if you remain attentive without losing your discernment.",
    "A better understanding of planetary energies will make your important decisions easier.",
    "The sky invites you to welcome change without giving up your inner stability.",
    "By moving forward with patience and clarity, you can transform these influences into genuine personal growth.",
],
  es: [
    "Los movimientos planetarios de este año crean un período de evolución, reflexión y ajuste. Algunas influencias actuarán rápidamente, mientras que otras transformarán gradualmente tu manera de avanzar.",
    "El cielo de este año pone de relieve varios ámbitos de tu vida. Los tránsitos planetarios te invitan a observar lo que evoluciona, lo que se resiste y lo que necesita una nueva dirección.",
    "Las influencias planetarias de los próximos meses podrían modificar tu ritmo, tus prioridades y tu percepción de ciertas situaciones.",
    "Este año está marcado por energías complementarias: algunas te impulsarán a actuar, mientras que otras te pedirán que reduzcas el ritmo y reflexiones.",
    "Los tránsitos del año favorecen una mejor comprensión de tus deseos, tus límites y los cambios que estás dispuesto a emprender.",
    "El clima planetario te acompaña en un período de evolución duradera. Una situación antigua podría abordarse con mayor madurez.",
    "Los próximos meses estarán influidos por varios movimientos celestes capaces de acentuar tu intuición, tu motivación o tu necesidad de cambio.",
    "Este año te invita a seguir los movimientos del cielo sin intentar controlar cada resultado. Algunas respuestas aparecerán progresivamente.",
    "Los tránsitos planetarios podrían revelar una oportunidad de crecimiento personal, relacional o profesional.",
    "El cielo de este año te anima a avanzar con flexibilidad. Los cambios más útiles podrían parecer incómodos al principio.",
    "El Sol refuerza tu necesidad de afirmar tus prioridades y concentrar tu energía en lo que realmente importa.",
    "El paso del Sol aporta mayor visibilidad a un proyecto o una decisión importante.",
    "La energía solar te anima a recuperar plenamente tu lugar.",
    "El Sol pone de relieve una situación que ya no podrás ignorar.",
    "Esta influencia favorece la confianza, la iniciativa y la afirmación personal.",
    "El Sol te impulsa a reconocer lo que te motiva profundamente.",
    "Comienza un período de renovación bajo esta influencia.",
    "El Sol favorece las situaciones en las que debes asumir mayores responsabilidades.",
    "Esta influencia te ayuda a aclarar la dirección que deseas dar a tu año.",
    "El paso del Sol podría reavivar tu ambición y tu creatividad.",
    "Mercurio favorece las conversaciones importantes, el aprendizaje y las decisiones reflexionadas.",
    "Una conversación podría aclarar una situación que lleva mucho tiempo siendo ambigua.",
    "Mercurio te invita a verificar la información antes de tomar cualquier decisión importante.",
    "Habrá muchos intercambios, pero los detalles exigirán mayor atención.",
    "Esta influencia favorece los proyectos de escritura, comunicación y negociación.",
    "Una información inesperada podría modificar tu visión de un proyecto.",
    "Mercurio te anima a hacer las preguntas adecuadas.",
    "Tu mente estará especialmente activa durante varios períodos del año.",
    "Las decisiones racionales se verán favorecidas sin dejar de lado tu intuición.",
    "Un desplazamiento o un encuentro podría influir de manera duradera en tu evolución.",
    "Venus suaviza el clima relacional y favorece los acercamientos.",
    "Podrías buscar mayor armonía en tus relaciones.",
    "Venus pone de relieve tu necesidad de afecto y reconocimiento.",
    "Esta influencia favorece las conversaciones sinceras y las reconciliaciones.",
    "Venus podría transformar tu relación con el amor, el dinero o tu autoestima.",
    "Un encuentro podría adquirir una importancia inesperada.",
    "La creatividad y los placeres sencillos serán más valorados.",
    "Podrías sentir una necesidad más fuerte de estabilidad afectiva.",
    "Venus recuerda que la armonía nunca debe construirse a costa de tus límites.",
    "Esta influencia reforzará progresivamente tu confianza.",
    "Marte aumenta tu motivación y tu deseo de actuar.",
    "Una situación podría requerir más valor y determinación.",
    "Marte te impulsa a transformar tus intenciones en acciones concretas.",
    "Esta influencia podría acentuar tu impaciencia si te falta preparación.",
    "Los proyectos que exijan energía y perseverancia se verán favorecidos.",
    "Podrías sentir una necesidad creciente de independencia.",
    "Marte te anima a defender tus necesidades con seguridad.",
    "Una nueva energía podría reactivar un antiguo proyecto.",
    "Una mejor gestión de tu impulsividad será esencial.",
    "Marte podría darte el impulso necesario para superar una etapa importante.",
    "Júpiter favorece la expansión, el aprendizaje y las nuevas posibilidades.",
    "Una situación podría evolucionar más favorablemente de lo previsto.",
    "Júpiter te anima a pensar en grande sin dejar de ser realista.",
    "Una oportunidad de crecimiento podría transformar tu trayectoria.",
    "Los viajes, los estudios y los nuevos proyectos se verán favorecidos.",
    "Esta influencia reforzará progresivamente tu confianza.",
    "Una persona con experiencia podría desempeñar un papel importante.",
    "Los proyectos a largo plazo recibirán un apoyo especial.",
    "Una puerta podría abrirse si aceptas salir de tu zona de confort.",
    "Júpiter te invita a reconocer las oportunidades sin idealizarlas.",
    "Saturno exige mayor disciplina y constancia.",
    "Una responsabilidad importante podría volverse más exigente, pero también más constructiva.",
    "Esta influencia te invita a consolidar tus bases antes de acelerar.",
    "Una aparente desaceleración podría preparar un éxito más sólido.",
    "Los resultados duraderos requerirán paciencia y perseverancia.",
    "Un límite se volverá más visible para favorecer una mejor organización.",
    "Los compromisos serios se verán especialmente favorecidos.",
    "Ciertas restricciones prepararán tu éxito futuro.",
    "Saturno te anima a proteger tu energía con mayor discernimiento.",
    "Una dificultad persistente podría terminar convirtiéndose en una fortaleza.",
    "Los planetas lentos trabajan en profundidad y transformarán gradualmente tu evolución.",
    "Urano, Neptuno y Plutón acentúan un cambio que ya ha comenzado.",
    "Una influencia sutil modificará tu intuición y tu percepción.",
    "Estos planetas te invitan a abandonar gradualmente ciertos hábitos.",
    "Urano favorecerá las sorpresas, mientras que Neptuno exigirá mayor discernimiento.",
    "Plutón acompañará una profunda transformación interior.",
    "Estas influencias producen sus efectos a lo largo de varios meses.",
    "Una antigua manera de funcionar podría desaparecer progresivamente.",
    "Los cambios más profundos serán a menudo los más discretos.",
    "Una toma de conciencia podría convertirse en el punto de partida de una nueva etapa de vida.",
    "La influencia dominante del año te impulsa a encontrar un mejor equilibrio entre acción y reflexión.",
    "El tema central se refiere a tu capacidad para avanzar sin perder tu estabilidad interior.",
    "La energía dominante favorece las decisiones reflexionadas y los ajustes duraderos.",
    "Este año pone un énfasis especial en la confianza y la comunicación.",
    "La principal influencia planetaria te invita a transformar una duda en una decisión.",
    "La energía general podría ayudarte a salir de un largo período de espera.",
    "El clima astrológico favorece una evolución progresiva en lugar de un cambio brusco.",
    "Tu principal lección será actuar en el momento adecuado.",
    "El cielo te anima a reconocer las oportunidades manteniéndote atento a los detalles.",
    "Esta influencia dominante te ayudará a aclarar tus verdaderas prioridades.",
    "Observa los cambios de ritmo sin intentar resistirte automáticamente.",
    "Utiliza los períodos dinámicos para actuar y los períodos más lentos para preparar lo que viene después.",
    "No confundas una emoción pasajera con una verdad definitiva.",
    "Mantente atento a los encuentros y a la información importante.",
    "Date tiempo cuando varias influencias parezcan contradictorias.",
    "Algunas evoluciones necesitarán varios meses antes de revelar todo su significado.",
    "Apóyate en los hechos dejando al mismo tiempo un espacio razonable a tu intuición.",
    "Aprovecha el impulso planetario para avanzar en una prioridad esencial.",
    "Acepta revisar una estrategia si las circunstancias cambian.",
    "Considera los tránsitos como guías y no como certezas absolutas.",
    "Los tránsitos de este año pueden ayudarte a avanzar con mayor conciencia, flexibilidad y confianza.",
    "El cielo te acompaña en un período de evolución capaz de producir efectos duraderos.",
    "Podrías terminar el año con una visión mucho más clara de tu futuro.",
    "Las influencias planetarias recuerdan que cada período tiene su propio ritmo.",
    "Una evolución importante podría comenzar discretamente antes de hacerse evidente.",
    "Este año te ofrece la oportunidad de utilizar los movimientos del cielo como un verdadero apoyo.",
    "Los tránsitos favorecerán tu progreso si permaneces atento sin perder tu discernimiento.",
    "Una mejor comprensión de las energías planetarias facilitará tus decisiones importantes.",
    "El cielo te invita a aceptar el cambio sin renunciar a tu estabilidad interior.",
    "Avanzando con paciencia y lucidez, podrás transformar estas influencias en un verdadero crecimiento personal.",
],
  de: [
    "Die planetarischen Bewegungen dieses Jahres schaffen eine Phase der Entwicklung, Reflexion und Anpassung. Manche Einflüsse wirken schnell, während andere Ihre Art voranzugehen allmählich verändern.",
    "Der Himmel dieses Jahres rückt mehrere Lebensbereiche in den Mittelpunkt. Die planetarischen Transite laden Sie dazu ein, zu beobachten, was sich entwickelt, was Widerstand leistet und was eine neue Richtung braucht.",
    "Die planetarischen Einflüsse der kommenden Monate könnten Ihr Tempo, Ihre Prioritäten und Ihre Wahrnehmung bestimmter Situationen verändern.",
    "Dieses Jahr ist von sich ergänzenden Energien geprägt: Manche werden Sie zum Handeln bewegen, andere werden Sie auffordern, langsamer zu werden und nachzudenken.",
    "Die Transite des Jahres fördern ein besseres Verständnis Ihrer Wünsche, Ihrer Grenzen und der Veränderungen, zu denen Sie bereit sind.",
    "Das planetarische Klima begleitet Sie durch eine Phase nachhaltiger Entwicklung. Eine alte Situation könnte mit größerer Reife angegangen werden.",
    "Die kommenden Monate werden von mehreren Himmelsbewegungen beeinflusst, die Ihre Intuition, Motivation oder Ihren Veränderungswunsch verstärken können.",
    "Dieses Jahr lädt Sie dazu ein, den Bewegungen des Himmels zu folgen, ohne jedes Ergebnis kontrollieren zu wollen. Manche Antworten werden sich nach und nach zeigen.",
    "Planetarische Transite könnten eine Chance für persönliches, zwischenmenschliches oder berufliches Wachstum sichtbar machen.",
    "Der Himmel dieses Jahres ermutigt Sie, flexibel voranzugehen. Die nützlichsten Veränderungen könnten sich zunächst unangenehm anfühlen.",
    "Die Sonne stärkt Ihr Bedürfnis, Ihre Prioritäten zu vertreten und Ihre Energie auf das zu richten, was wirklich zählt.",
    "Der Durchgang der Sonne verleiht einem wichtigen Projekt oder einer Entscheidung mehr Sichtbarkeit.",
    "Die Sonnenenergie ermutigt Sie, Ihren Platz wieder vollständig einzunehmen.",
    "Die Sonne beleuchtet eine Situation, die Sie nicht länger ignorieren können.",
    "Dieser Einfluss fördert Selbstvertrauen, Initiative und Selbstbehauptung.",
    "Die Sonne bringt Sie dazu, zu erkennen, was Sie im Innersten motiviert.",
    "Unter diesem Einfluss beginnt eine Phase der Erneuerung.",
    "Die Sonne begünstigt Situationen, in denen Sie mehr Verantwortung übernehmen müssen.",
    "Dieser Einfluss hilft Ihnen, die Richtung zu klären, die Sie Ihrem Jahr geben möchten.",
    "Der Sonneneinfluss könnte Ihren Ehrgeiz und Ihre Kreativität neu entfachen.",
    "Merkur begünstigt wichtige Gespräche, Lernen und wohlüberlegte Entscheidungen.",
    "Ein Gespräch könnte eine Situation klären, die lange unklar geblieben ist.",
    "Merkur lädt Sie dazu ein, Informationen vor jeder wichtigen Entscheidung zu überprüfen.",
    "Es wird viele Gespräche geben, doch Details verlangen größere Aufmerksamkeit.",
    "Dieser Einfluss unterstützt Projekte rund um Schreiben, Kommunikation und Verhandlung.",
    "Eine unerwartete Information könnte Ihre Sicht auf ein Projekt verändern.",
    "Merkur ermutigt Sie, die richtigen Fragen zu stellen.",
    "Ihr Geist wird in mehreren Phasen des Jahres besonders aktiv sein.",
    "Rationale Entscheidungen werden begünstigt, ohne Ihre Intuition zu vernachlässigen.",
    "Eine Reise oder Begegnung könnte Ihre Entwicklung nachhaltig beeinflussen.",
    "Venus mildert das Beziehungsklima und begünstigt Annäherungen.",
    "Sie könnten nach mehr Harmonie in Ihren Beziehungen suchen.",
    "Venus rückt Ihr Bedürfnis nach Zuneigung und Anerkennung in den Mittelpunkt.",
    "Dieser Einfluss begünstigt aufrichtige Gespräche und Versöhnungen.",
    "Venus könnte Ihr Verhältnis zu Liebe, Geld oder Selbstwert verändern.",
    "Eine Begegnung könnte unerwartet wichtig werden.",
    "Kreativität und einfache Freuden werden stärker geschätzt.",
    "Sie könnten ein stärkeres Bedürfnis nach emotionaler Stabilität verspüren.",
    "Venus erinnert daran, dass Harmonie niemals auf Kosten Ihrer Grenzen entstehen sollte.",
    "Dieser Einfluss wird Ihr Selbstvertrauen nach und nach stärken.",
    "Mars steigert Ihre Motivation und Ihren Wunsch zu handeln.",
    "Eine Situation könnte mehr Mut und Entschlossenheit verlangen.",
    "Mars drängt Sie dazu, Ihre Absichten in konkrete Handlungen umzusetzen.",
    "Dieser Einfluss könnte Ihre Ungeduld verstärken, wenn es Ihnen an Vorbereitung fehlt.",
    "Projekte, die Energie und Ausdauer verlangen, werden begünstigt.",
    "Sie könnten ein stärkeres Bedürfnis nach Unabhängigkeit verspüren.",
    "Mars ermutigt Sie, Ihre Bedürfnisse selbstbewusst zu vertreten.",
    "Neue Energie könnte ein altes Projekt wiederbeleben.",
    "Ein besserer Umgang mit Ihrer Impulsivität wird wesentlich.",
    "Mars könnte Ihnen den nötigen Schwung geben, um eine wichtige Etappe zu überwinden.",
    "Jupiter begünstigt Expansion, Lernen und neue Möglichkeiten.",
    "Eine Situation könnte sich günstiger entwickeln als erwartet.",
    "Jupiter ermutigt Sie, größer zu denken und dennoch realistisch zu bleiben.",
    "Eine Wachstumschance könnte Ihren Weg verändern.",
    "Reisen, Studien und neue Projekte werden begünstigt.",
    "Dieser Einfluss wird Ihr Selbstvertrauen nach und nach stärken.",
    "Eine erfahrene Person könnte eine wichtige Rolle spielen.",
    "Langfristige Projekte werden besondere Unterstützung erhalten.",
    "Eine Tür könnte sich öffnen, wenn Sie bereit sind, Ihre Komfortzone zu verlassen.",
    "Jupiter lädt Sie dazu ein, Chancen zu erkennen, ohne sie zu idealisieren.",
    "Saturn verlangt mehr Disziplin und Beständigkeit.",
    "Eine wichtige Verantwortung könnte anspruchsvoller, aber auch konstruktiver werden.",
    "Dieser Einfluss lädt Sie dazu ein, Ihre Grundlagen zu festigen, bevor Sie beschleunigen.",
    "Eine scheinbare Verlangsamung könnte einen stabileren Erfolg vorbereiten.",
    "Dauerhafte Ergebnisse werden Geduld und Ausdauer erfordern.",
    "Eine Grenze wird sichtbarer werden, um eine bessere Organisation zu fördern.",
    "Ernsthafte Verpflichtungen werden besonders begünstigt.",
    "Bestimmte Einschränkungen werden Ihren zukünftigen Erfolg vorbereiten.",
    "Saturn ermutigt Sie, Ihre Energie mit größerem Urteilsvermögen zu schützen.",
    "Eine anhaltende Schwierigkeit könnte schließlich zu einer Stärke werden.",
    "Die langsamen Planeten wirken in der Tiefe und werden Ihre Entwicklung allmählich verändern.",
    "Uranus, Neptun und Pluto verstärken eine Veränderung, die bereits begonnen hat.",
    "Ein subtiler Einfluss wird Ihre Intuition und Wahrnehmung verändern.",
    "Diese Planeten laden Sie dazu ein, bestimmte Gewohnheiten schrittweise loszulassen.",
    "Uranus begünstigt Überraschungen, während Neptun mehr Urteilsvermögen verlangt.",
    "Pluto begleitet eine tiefgreifende innere Transformation.",
    "Diese Einflüsse entfalten ihre Wirkung über mehrere Monate hinweg.",
    "Eine alte Funktionsweise könnte nach und nach verschwinden.",
    "Die tiefgreifendsten Veränderungen werden oft die unauffälligsten sein.",
    "Eine Erkenntnis könnte zum Ausgangspunkt einer neuen Lebensphase werden.",
    "Der dominierende Einfluss des Jahres drängt Sie dazu, ein besseres Gleichgewicht zwischen Handeln und Nachdenken zu finden.",
    "Das zentrale Thema betrifft Ihre Fähigkeit, voranzugehen, ohne Ihre innere Stabilität zu verlieren.",
    "Die dominierende Energie begünstigt wohlüberlegte Entscheidungen und nachhaltige Anpassungen.",
    "Dieses Jahr legt besonderen Wert auf Vertrauen und Kommunikation.",
    "Der wichtigste planetarische Einfluss lädt Sie dazu ein, Zögern in eine Entscheidung zu verwandeln.",
    "Die allgemeine Energie könnte Ihnen helfen, eine lange Wartephase zu verlassen.",
    "Das astrologische Klima begünstigt eine schrittweise Entwicklung statt eines plötzlichen Umbruchs.",
    "Ihre wichtigste Lektion wird darin bestehen, im richtigen Moment zu handeln.",
    "Der Himmel ermutigt Sie, Chancen zu erkennen und gleichzeitig auf Details zu achten.",
    "Dieser dominierende Einfluss wird Ihnen helfen, Ihre wahren Prioritäten zu klären.",
    "Beobachten Sie Veränderungen im Tempo, ohne automatisch dagegen anzukämpfen.",
    "Nutzen Sie dynamische Phasen zum Handeln und langsamere Phasen, um das Kommende vorzubereiten.",
    "Verwechseln Sie eine vorübergehende Emotion nicht mit einer endgültigen Wahrheit.",
    "Bleiben Sie aufmerksam für Begegnungen und wichtige Informationen.",
    "Geben Sie sich Zeit, wenn mehrere Einflüsse widersprüchlich erscheinen.",
    "Manche Entwicklungen brauchen mehrere Monate, bevor sie ihre ganze Bedeutung zeigen.",
    "Stützen Sie sich auf Fakten und lassen Sie zugleich vernünftigen Raum für Ihre Intuition.",
    "Nutzen Sie den planetarischen Schwung, um bei einer wesentlichen Priorität voranzukommen.",
    "Seien Sie bereit, eine Strategie zu überdenken, wenn sich die Umstände ändern.",
    "Betrachten Sie Transite als Orientierungshilfen und nicht als absolute Gewissheiten.",
    "Die Transite dieses Jahres können Ihnen helfen, mit mehr Bewusstsein, Flexibilität und Vertrauen voranzugehen.",
    "Der Himmel begleitet Sie durch eine Phase der Entwicklung, die nachhaltige Wirkungen entfalten kann.",
    "Sie könnten das Jahr mit einer deutlich klareren Vorstellung von Ihrer Zukunft beenden.",
    "Die planetarischen Einflüsse erinnern daran, dass jede Phase ihren eigenen Rhythmus hat.",
    "Eine wichtige Entwicklung könnte unauffällig beginnen, bevor sie offensichtlich wird.",
    "Dieses Jahr bietet Ihnen die Möglichkeit, die Bewegungen des Himmels als echte Unterstützung zu nutzen.",
    "Die Transite werden Ihren Fortschritt fördern, wenn Sie aufmerksam bleiben, ohne Ihr Urteilsvermögen zu verlieren.",
    "Ein besseres Verständnis der planetarischen Energien wird wichtige Entscheidungen erleichtern.",
    "Der Himmel lädt Sie dazu ein, Veränderungen anzunehmen, ohne Ihre innere Stabilität aufzugeben.",
    "Wenn Sie mit Geduld und Klarheit vorangehen, können Sie diese Einflüsse in echtes persönliches Wachstum verwandeln.",
],
  it: [
    "I movimenti planetari di quest’anno creano un periodo di evoluzione, riflessione e adattamento. Alcune influenze agiranno rapidamente, mentre altre trasformeranno gradualmente il vostro modo di avanzare.",
    "Il cielo di quest’anno mette in luce diversi ambiti della vostra vita. I transiti planetari vi invitano a osservare ciò che evolve, ciò che resiste e ciò che richiede una nuova direzione.",
    "Le influenze planetarie dei prossimi mesi potrebbero modificare il vostro ritmo, le vostre priorità e la percezione di alcune situazioni.",
    "Quest’anno è segnato da energie complementari: alcune vi spingeranno ad agire, mentre altre vi chiederanno di rallentare e riflettere.",
    "I transiti dell’anno favoriscono una migliore comprensione dei vostri desideri, dei vostri limiti e dei cambiamenti che siete pronti a intraprendere.",
    "Il clima planetario vi accompagna in un periodo di evoluzione duratura. Una situazione passata potrebbe essere affrontata con maggiore maturità.",
    "I prossimi mesi saranno influenzati da diversi movimenti celesti capaci di accentuare la vostra intuizione, motivazione o bisogno di cambiamento.",
    "Quest’anno vi invita a seguire i movimenti del cielo senza cercare di controllare ogni risultato. Alcune risposte appariranno gradualmente.",
    "I transiti planetari potrebbero rivelare un’opportunità di crescita personale, relazionale o professionale.",
    "Il cielo di quest’anno vi incoraggia ad avanzare con flessibilità. I cambiamenti più utili potrebbero inizialmente sembrare scomodi.",
    "Il Sole rafforza il vostro bisogno di affermare le priorità e concentrare l’energia su ciò che conta davvero.",
    "Il passaggio del Sole porta maggiore visibilità a un progetto o a una decisione importante.",
    "L’energia solare vi incoraggia a riprendere pienamente il vostro posto.",
    "Il Sole mette in luce una situazione che non potrete più ignorare.",
    "Questa influenza favorisce fiducia, iniziativa e affermazione personale.",
    "Il Sole vi spinge a riconoscere ciò che vi motiva profondamente.",
    "Sotto questa influenza inizia un periodo di rinnovamento.",
    "Il Sole favorisce le situazioni in cui dovete assumere maggiori responsabilità.",
    "Questa influenza vi aiuta a chiarire la direzione che desiderate dare al vostro anno.",
    "Il passaggio del Sole potrebbe riaccendere la vostra ambizione e creatività.",
    "Mercurio favorisce le conversazioni importanti, l’apprendimento e le decisioni ponderate.",
    "Una conversazione potrebbe chiarire una situazione rimasta ambigua per molto tempo.",
    "Mercurio vi invita a verificare le informazioni prima di qualsiasi decisione importante.",
    "Gli scambi saranno numerosi, ma i dettagli richiederanno maggiore attenzione.",
    "Questa influenza sostiene i progetti di scrittura, comunicazione e negoziazione.",
    "Un’informazione inattesa potrebbe modificare la vostra visione di un progetto.",
    "Mercurio vi incoraggia a porre le domande giuste.",
    "La vostra mente sarà particolarmente attiva durante diversi periodi dell’anno.",
    "Le decisioni razionali saranno favorite senza trascurare la vostra intuizione.",
    "Uno spostamento o un incontro potrebbe influenzare in modo duraturo la vostra evoluzione.",
    "Venere addolcisce il clima relazionale e favorisce gli avvicinamenti.",
    "Potreste cercare maggiore armonia nelle vostre relazioni.",
    "Venere mette in luce il vostro bisogno di affetto e riconoscimento.",
    "Questa influenza favorisce le conversazioni sincere e le riconciliazioni.",
    "Venere potrebbe trasformare il vostro rapporto con l’amore, il denaro o l’autostima.",
    "Un incontro potrebbe assumere un’importanza inattesa.",
    "La creatività e i piaceri semplici saranno maggiormente valorizzati.",
    "Potreste sentire un bisogno più forte di stabilità affettiva.",
    "Venere ricorda che l’armonia non deve mai essere costruita a discapito dei vostri limiti.",
    "Questa influenza rafforzerà gradualmente la vostra fiducia.",
    "Marte aumenta la vostra motivazione e il desiderio di agire.",
    "Una situazione potrebbe richiedere maggiore coraggio e determinazione.",
    "Marte vi spinge a trasformare le intenzioni in azioni concrete.",
    "Questa influenza potrebbe accentuare la vostra impazienza se manca la preparazione.",
    "I progetti che richiedono energia e perseveranza saranno favoriti.",
    "Potreste sentire un bisogno crescente di indipendenza.",
    "Marte vi incoraggia a difendere i vostri bisogni con sicurezza.",
    "Una nuova energia potrebbe rilanciare un vecchio progetto.",
    "Una migliore gestione dell’impulsività diventerà essenziale.",
    "Marte potrebbe darvi lo slancio necessario per superare una tappa importante.",
    "Giove favorisce l’espansione, l’apprendimento e le nuove possibilità.",
    "Una situazione potrebbe evolvere più favorevolmente del previsto.",
    "Giove vi incoraggia a pensare in grande pur rimanendo realistici.",
    "Un’opportunità di crescita potrebbe trasformare il vostro percorso.",
    "Viaggi, studi e nuovi progetti saranno favoriti.",
    "Questa influenza rafforzerà gradualmente la vostra fiducia.",
    "Una persona esperta potrebbe svolgere un ruolo importante.",
    "I progetti a lungo termine beneficeranno di un sostegno particolare.",
    "Una porta potrebbe aprirsi se accettate di uscire dalla vostra zona di comfort.",
    "Giove vi invita a riconoscere le opportunità senza idealizzarle.",
    "Saturno richiede maggiore disciplina e costanza.",
    "Una responsabilità importante potrebbe diventare più impegnativa ma anche più costruttiva.",
    "Questa influenza vi invita a consolidare le basi prima di accelerare.",
    "Un rallentamento apparente potrebbe preparare un successo più solido.",
    "I risultati duraturi richiederanno pazienza e perseveranza.",
    "Un limite diventerà più visibile per favorire una migliore organizzazione.",
    "Gli impegni seri saranno particolarmente favoriti.",
    "Alcuni vincoli prepareranno il vostro successo futuro.",
    "Saturno vi incoraggia a proteggere la vostra energia con maggiore discernimento.",
    "Una difficoltà persistente potrebbe infine diventare una forza.",
    "I pianeti lenti agiscono in profondità e trasformeranno gradualmente la vostra evoluzione.",
    "Urano, Nettuno e Plutone accentuano un cambiamento già iniziato.",
    "Un’influenza sottile modificherà la vostra intuizione e percezione.",
    "Questi pianeti vi invitano ad abbandonare gradualmente alcune abitudini.",
    "Urano favorirà le sorprese, mentre Nettuno richiederà maggiore discernimento.",
    "Plutone accompagnerà una profonda trasformazione interiore.",
    "Queste influenze producono i loro effetti nel corso di diversi mesi.",
    "Un vecchio modo di funzionare potrebbe scomparire gradualmente.",
    "I cambiamenti più profondi saranno spesso i più discreti.",
    "Una presa di coscienza potrebbe diventare il punto di partenza di una nuova fase della vita.",
    "L’influenza dominante dell’anno vi spinge a trovare un equilibrio migliore tra azione e riflessione.",
    "Il tema centrale riguarda la vostra capacità di avanzare senza perdere la stabilità interiore.",
    "L’energia dominante favorisce decisioni ponderate e adattamenti duraturi.",
    "Quest’anno pone particolare enfasi sulla fiducia e sulla comunicazione.",
    "La principale influenza planetaria vi invita a trasformare un’esitazione in una decisione.",
    "L’energia generale potrebbe aiutarvi a uscire da un lungo periodo di attesa.",
    "Il clima astrologico favorisce un’evoluzione graduale piuttosto che uno sconvolgimento improvviso.",
    "La vostra lezione principale sarà agire al momento giusto.",
    "Il cielo vi incoraggia a riconoscere le aperture rimanendo attenti ai dettagli.",
    "Questa influenza dominante vi aiuterà a chiarire le vostre vere priorità.",
    "Osservate i cambiamenti di ritmo senza cercare di opporvi automaticamente.",
    "Utilizzate i periodi dinamici per agire e quelli più lenti per preparare ciò che verrà.",
    "Non scambiate un’emozione passeggera per una verità definitiva.",
    "Rimanete attenti agli incontri e alle informazioni importanti.",
    "Concedetevi tempo quando diverse influenze sembrano contraddirsi.",
    "Alcune evoluzioni avranno bisogno di diversi mesi prima di rivelare tutto il loro significato.",
    "Basatevi sui fatti lasciando comunque uno spazio ragionevole alla vostra intuizione.",
    "Sfruttate lo slancio planetario per avanzare su una priorità essenziale.",
    "Accettate di rivedere una strategia se le circostanze cambiano.",
    "Considerate i transiti come guide piuttosto che come certezze assolute.",
    "I transiti di quest’anno possono aiutarvi ad avanzare con maggiore consapevolezza, flessibilità e fiducia.",
    "Il cielo vi accompagna in un periodo di evoluzione capace di produrre effetti duraturi.",
    "Potreste terminare l’anno con una visione molto più chiara del vostro futuro.",
    "Le influenze planetarie ricordano che ogni periodo possiede il proprio ritmo.",
    "Un’evoluzione importante potrebbe iniziare in modo discreto prima di diventare evidente.",
    "Quest’anno vi offre l’opportunità di utilizzare i movimenti del cielo come un vero sostegno.",
    "I transiti favoriranno i vostri progressi se rimarrete attenti senza perdere il discernimento.",
    "Una migliore comprensione delle energie planetarie faciliterà le vostre decisioni importanti.",
    "Il cielo vi invita ad accogliere il cambiamento senza rinunciare alla vostra stabilità interiore.",
    "Avanzando con pazienza e lucidità, potrete trasformare queste influenze in una vera crescita personale.",
],
  pt: [
    "Os movimentos planetários deste ano criam um período de evolução, reflexão e ajustes. Algumas influências agirão rapidamente, enquanto outras transformarão gradualmente sua maneira de avançar.",
    "O céu deste ano destaca várias áreas da sua vida. Os trânsitos planetários convidam você a observar o que está evoluindo, o que resiste e o que precisa de uma nova direção.",
    "As influências planetárias dos próximos meses poderão modificar seu ritmo, suas prioridades e sua percepção de certas situações.",
    "Este ano é marcado por energias complementares: algumas incentivarão você a agir, enquanto outras pedirão que diminua o ritmo e reflita.",
    "Os trânsitos do ano favorecem uma melhor compreensão dos seus desejos, dos seus limites e das mudanças que você está pronto para realizar.",
    "O clima planetário acompanha você em um período de evolução duradoura. Uma situação antiga poderá ser abordada com mais maturidade.",
    "Os próximos meses serão influenciados por vários movimentos celestes capazes de intensificar sua intuição, motivação ou necessidade de mudança.",
    "Este ano convida você a acompanhar os movimentos do céu sem tentar controlar cada resultado. Algumas respostas aparecerão gradualmente.",
    "Os trânsitos planetários poderão revelar uma oportunidade de crescimento pessoal, relacional ou profissional.",
    "O céu deste ano incentiva você a avançar com flexibilidade. As mudanças mais úteis poderão parecer desconfortáveis no início.",
    "O Sol reforça sua necessidade de afirmar suas prioridades e concentrar sua energia no que realmente importa.",
    "A passagem do Sol traz mais visibilidade para um projeto ou decisão importante.",
    "A energia solar incentiva você a ocupar plenamente o seu espaço.",
    "O Sol ilumina uma situação que você não poderá mais ignorar.",
    "Esta influência favorece confiança, iniciativa e afirmação pessoal.",
    "O Sol incentiva você a reconhecer o que realmente o motiva.",
    "Um período de renovação começa sob esta influência.",
    "O Sol favorece situações em que você precisa assumir mais responsabilidades.",
    "Esta influência ajuda você a esclarecer a direção que deseja dar ao seu ano.",
    "A passagem do Sol poderá reacender sua ambição e criatividade.",
    "Mercúrio favorece conversas importantes, aprendizado e decisões refletidas.",
    "Uma conversa poderá esclarecer uma situação que permaneceu ambígua por muito tempo.",
    "Mercúrio convida você a verificar as informações antes de qualquer decisão importante.",
    "Haverá muitas conversas, mas os detalhes exigirão mais atenção.",
    "Esta influência favorece projetos de escrita, comunicação e negociação.",
    "Uma informação inesperada poderá mudar sua visão de um projeto.",
    "Mercúrio incentiva você a fazer as perguntas certas.",
    "Sua mente estará especialmente ativa durante vários períodos do ano.",
    "Decisões racionais serão favorecidas sem que você deixe de lado sua intuição.",
    "Uma viagem ou um encontro poderá influenciar sua evolução de forma duradoura.",
    "Vênus suaviza o clima relacional e favorece aproximações.",
    "Você poderá buscar mais harmonia em seus relacionamentos.",
    "Vênus destaca sua necessidade de afeto e reconhecimento.",
    "Esta influência favorece conversas sinceras e reconciliações.",
    "Vênus poderá transformar sua relação com o amor, o dinheiro ou a autoestima.",
    "Um encontro poderá assumir uma importância inesperada.",
    "A criatividade e os prazeres simples serão mais valorizados.",
    "Você poderá sentir uma necessidade maior de estabilidade afetiva.",
    "Vênus lembra que a harmonia nunca deve ser construída à custa dos seus limites.",
    "Esta influência fortalecerá gradualmente sua confiança.",
    "Marte aumenta sua motivação e seu desejo de agir.",
    "Uma situação poderá exigir mais coragem e determinação.",
    "Marte incentiva você a transformar suas intenções em ações concretas.",
    "Esta influência poderá aumentar sua impaciência se faltar preparação.",
    "Projetos que exigem energia e perseverança serão favorecidos.",
    "Você poderá sentir uma necessidade maior de independência.",
    "Marte incentiva você a defender suas necessidades com confiança.",
    "Uma nova energia poderá reativar um antigo projeto.",
    "Uma melhor gestão da sua impulsividade se tornará essencial.",
    "Marte poderá dar a você o impulso necessário para superar uma etapa importante.",
    "Júpiter favorece expansão, aprendizado e novas possibilidades.",
    "Uma situação poderá evoluir de forma mais favorável do que o esperado.",
    "Júpiter incentiva você a pensar grande sem deixar de ser realista.",
    "Uma oportunidade de crescimento poderá transformar sua trajetória.",
    "Viagens, estudos e novos projetos serão favorecidos.",
    "Esta influência fortalecerá gradualmente sua confiança.",
    "Uma pessoa experiente poderá desempenhar um papel importante.",
    "Projetos de longo prazo receberão um apoio especial.",
    "Uma porta poderá se abrir se você aceitar sair da sua zona de conforto.",
    "Júpiter convida você a reconhecer as oportunidades sem idealizá-las.",
    "Saturno exige mais disciplina e constância.",
    "Uma responsabilidade importante poderá se tornar mais exigente, mas também mais construtiva.",
    "Esta influência convida você a consolidar suas bases antes de acelerar.",
    "Uma aparente desaceleração poderá preparar um sucesso mais sólido.",
    "Resultados duradouros exigirão paciência e perseverança.",
    "Um limite se tornará mais visível para favorecer uma organização melhor.",
    "Compromissos sérios serão especialmente favorecidos.",
    "Algumas restrições prepararão seu sucesso futuro.",
    "Saturno incentiva você a proteger sua energia com mais discernimento.",
    "Uma dificuldade persistente poderá acabar se tornando uma força.",
    "Os planetas lentos agem em profundidade e transformarão gradualmente sua evolução.",
    "Urano, Netuno e Plutão intensificam uma mudança que já começou.",
    "Uma influência sutil modificará sua intuição e percepção.",
    "Esses planetas convidam você a abandonar gradualmente certos hábitos.",
    "Urano favorecerá surpresas, enquanto Netuno exigirá mais discernimento.",
    "Plutão acompanhará uma profunda transformação interior.",
    "Essas influências produzem seus efeitos ao longo de vários meses.",
    "Uma antiga maneira de funcionar poderá desaparecer gradualmente.",
    "As mudanças mais profundas muitas vezes serão as mais discretas.",
    "Uma tomada de consciência poderá se tornar o ponto de partida de uma nova etapa de vida.",
    "A influência dominante do ano incentiva você a encontrar um equilíbrio melhor entre ação e reflexão.",
    "O tema central diz respeito à sua capacidade de avançar sem perder sua estabilidade interior.",
    "A energia dominante favorece decisões refletidas e ajustes duradouros.",
    "Este ano coloca um foco especial na confiança e na comunicação.",
    "A principal influência planetária convida você a transformar uma hesitação em decisão.",
    "A energia geral poderá ajudar você a sair de um longo período de espera.",
    "O clima astrológico favorece uma evolução gradual em vez de uma mudança brusca.",
    "Sua principal lição será agir no momento certo.",
    "O céu incentiva você a reconhecer oportunidades mantendo atenção aos detalhes.",
    "Esta influência dominante ajudará você a esclarecer suas verdadeiras prioridades.",
    "Observe as mudanças de ritmo sem tentar resistir automaticamente.",
    "Use os períodos dinâmicos para agir e os períodos mais lentos para preparar o que vem depois.",
    "Não confunda uma emoção passageira com uma verdade definitiva.",
    "Fique atento aos encontros e às informações importantes.",
    "Dê a si mesmo tempo quando várias influências parecerem contraditórias.",
    "Algumas evoluções precisarão de vários meses antes de revelar todo o seu significado.",
    "Apoie-se nos fatos, deixando ao mesmo tempo um espaço razoável para sua intuição.",
    "Aproveite o impulso planetário para avançar em uma prioridade essencial.",
    "Aceite rever uma estratégia se as circunstâncias mudarem.",
    "Considere os trânsitos como guias, e não como certezas absolutas.",
    "Os trânsitos deste ano podem ajudar você a avançar com mais consciência, flexibilidade e confiança.",
    "O céu acompanha você em um período de evolução capaz de produzir efeitos duradouros.",
    "Você poderá terminar o ano com uma visão muito mais clara do seu futuro.",
    "As influências planetárias lembram que cada período possui seu próprio ritmo.",
    "Uma evolução importante poderá começar discretamente antes de se tornar evidente.",
    "Este ano oferece a você a oportunidade de usar os movimentos do céu como um verdadeiro apoio.",
    "Os trânsitos favorecerão seu progresso se você permanecer atento sem perder o discernimento.",
    "Uma melhor compreensão das energias planetárias facilitará suas decisões importantes.",
    "O céu convida você a acolher a mudança sem abrir mão da sua estabilidade interior.",
    "Avançando com paciência e lucidez, você poderá transformar essas influências em verdadeiro crescimento pessoal.",
],
};

const TRANSIT_LABELS: Record<
  Exclude<PaidPdfLocale, "fr">,
  TranslationMap
> = {
  en: {
    "Influence de": "Influence of",
  },

  es: {
    "Influence de": "Influencia de",
  },

  de: {
    "Influence de": "Einfluss von",
  },

  it: {
    "Influence de": "Influenza di",
  },

  pt: {
    "Influence de": "Influência de",
  },
};

const TRANSIT_TITLES = Object.fromEntries(
  (["en", "es", "de", "it", "pt"] as const).map((locale) => [
    locale,
    buildTranslationMap(TRANSIT_TITLES_FR, TRANSIT_TITLES_TRANSLATIONS[locale]),
  ]),
) as Record<Exclude<PaidPdfLocale, "fr">, TranslationMap>;

const PLANET_LABELS = Object.fromEntries(
  (["en", "es", "de", "it", "pt"] as const).map((locale) => [
    locale,
    buildTranslationMap(PLANET_LABELS_FR, PLANET_LABELS_TRANSLATIONS[locale]),
  ]),
) as Record<Exclude<PaidPdfLocale, "fr">, TranslationMap>;

const TRANSIT_TEXTS = Object.fromEntries(
  (["en", "es", "de", "it", "pt"] as const).map((locale) => [
    locale,
    buildTranslationMap(TRANSIT_TEXTS_FR, TRANSIT_TEXTS_TRANSLATIONS[locale]),
  ]),
) as Record<Exclude<PaidPdfLocale, "fr">, TranslationMap>;

export function localizeYearHoroscopeTransit(
  source: string,
  locale: PaidPdfLocale,
): string {
  if (locale === "fr") {
    return source;
  }

  let output = source;

  output = applyTranslations(output, TRANSIT_TITLES[locale]);
  output = applyTranslations(output, PLANET_LABELS[locale]);
  output = applyTranslations(output, TRANSIT_TEXTS[locale]);
  output = applyTranslations(output, TRANSIT_LABELS[locale]);

  return output;
}
